In [1]:
import pandas as pd
from glob import glob

runs = glob("./mlruns/**/*.csv", recursive=True)

In [2]:
runs

['./mlruns/336576534199393390/bfcc62521ea74954beac89638536a951/artifacts/commandr-104B-big_subj_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/336576534199393390/8b56917191e34e53b63d010c4ce280a8/artifacts/mistral-22B-medium_subj_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/336576534199393390/000f0130bcca47edb615e50749baa919/artifacts/commandr-7B-small_subj_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/336576534199393390/e00c4d6e195c4e82a4d7f70bcf2fb9d0/artifacts/qwen2.5-72B-big_subj_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/336576534199393390/444bedbd45354bc4bea5b312a4250ee7/artifacts/olmo-7B-small_subj_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/336576534199393390/868a04798d2448bab5a133913d457b6d/artifacts/mistral-7B-small_subj_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/336576534199393390/39d43e70d0eb4ab6aff2238880a57b75/artifacts/mistral-7B-small_subj_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/336576534199393390/d51f65ceef7b4a6eb1904cc4a3ee19a7/artifacts/commandr-7B-small_subj_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/336576534199393390/0f9b3ff35b6246fa9ec946630b9bbb16/artifacts/qwen2.5-7B-small_subj_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/336576534199393390/144f47e548114705a3b6a9fb40209e0f/artifacts/llama-70B-big_subj_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/336576534199393390/802101e721c64e8fac3823f2175f3fbf/artifacts/commandr-104B-big_subj_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/336576534199393390/7e04bbc392f14123a195f745407f3440/artifacts/olmo2-32B-medium_subj_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/336576534199393390/be7f3e5463394dd699f0343d728788bc/artifacts/commandr-7B-small_subj_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/336576534199393390/90672948eb954ff58c1ae3d70602d035/artifacts/mistral-22B-medium_subj_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/336576534199393390/317980b5395e41749991b7e42ceb38cb/artifacts/mixtral-8x22B-medium_subj_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/336576534199393390/39f784ade46044e8a7011956ab31e3db/artifacts/llama-8B-small_subj_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/336576534199393390/e12e29de4eba41249d5789f57783565e/artifacts/qwen2.5-7B-small_subj_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/336576534199393390/3ef0c83b36a4426cb6c448c74ecf1e84/artifacts/mixtral-8x7B-small_subj_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/336576534199393390/ffad0a26799d4b88a19f1593e745f25e/artifacts/olmo2-32B-medium_subj_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/336576534199393390/6594bd02253b4e29b1489e7013a2fce6/artifacts/mistral-7B-small_subj_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/336576534199393390/860d7632a8354760a7a2b5e5a1b1292b/artifacts/mistral-22B-medium_subj_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/336576534199393390/9a7ddea9967c4f779b9093229405d1ec/artifacts/llama-8B-small_subj_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/336576534199393390/92af3709fdd84d7ba7c9b5f24c8ad16b/artifacts/mixtral-8x7B-small_subj_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/336576534199393390/b9c42868b99447b7b53531c77fe7aeef/artifacts/olmo2-32B-medium_subj_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/336576534199393390/12f911f3cda844a590709088b0750071/artifacts/olmo-7B-small_subj_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/336576534199393390/61ce5a42edae4c6b874e098b06d3499b/artifacts/qwen2.5-72B-big_subj_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/763756296835180967/42718aa5c1734282b1d5f86be12abed3/artifacts/mixtral-8x7B-small_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/763756296835180967/22493e1f462142fc8b671e105e706036/artifacts/olmo2-32B-medium_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/763756296835180967/3229a4dfda934fda830d0b2effb0298f/artifacts/olmo-7B-small_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/763756296835180967/a8a9c0451b49433ea5cd920fb68e3649/artifacts/mistral-22B-medium_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/763756296835180967/d8c0afbd8c6b461496d8e323aea7d846/artifacts/mistral-22B-medium_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/763756296835180967/50e85531013f40d7abf041c6ff338351/artifacts/olmo-7B-small_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/763756296835180967/7cff17b88ad94faa9464b2947940a2d0/artifacts/mistral-7B-small_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/763756296835180967/4d0f4bdc75d74ee6a1f69beaa5103388/artifacts/llama-8B-small_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/763756296835180967/2cb5a96289a54a4a84c4934163cf226b/artifacts/commandr-7B-small_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/763756296835180967/ce0707c1e3a0426fbe226774ceac01f7/artifacts/llama-70B-big_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/763756296835180967/a66c91e48b0840ed9182bd75fdebbb67/artifacts/olmo-7B-small_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/763756296835180967/ea51bb6edb6c4e79aa215663adb22c13/artifacts/mixtral-8x22B-medium_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/763756296835180967/7e952d9fd707440ca0c36e127482cc56/artifacts/commandr-7B-small_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/763756296835180967/d3c2a2ee237648b58324fc4cfc87346a/artifacts/mistral-22B-medium_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/763756296835180967/255fd733ab3641e19f95c1823ef5923c/artifacts/mixtral-8x22B-big_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/763756296835180967/95f14e05f4de44b5bc8de54beeb797e8/artifacts/mistral-7B-small_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/763756296835180967/31589a761eff46f29f25be22e615ea84/artifacts/olmo2-32B-medium_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/763756296835180967/42d9ae35ca4f4d1db16008bdbfc7a9f7/artifacts/llama-8B-small_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/763756296835180967/13e8d5a7a90f4df7955bd560ce954cb9/artifacts/mistral-7B-small_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/763756296835180967/daee506eb3694b5788a3ad4dc79be07f/artifacts/llama-8B-small_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/763756296835180967/2686e66957324dcebb68e7e14209461d/artifacts/qwen2.5-7B-small_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/763756296835180967/bf33baec21b542a2a17bdced8275fa8b/artifacts/qwen2.5-7B-small_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/763756296835180967/c9dcabb0dbde4746b2dfe72c56d24245/artifacts/llama-70B-big_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/763756296835180967/dd527efae34c42ab82196cc6f0da9595/artifacts/mistral-22B-medium_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/763756296835180967/99977df7b2044889b1c188ea7941ae5f/artifacts/commandr-104B-big_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/763756296835180967/e6ca32e4ac724205aeca7c9f7d5ac015/artifacts/qwen2.5-72B-big_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/763756296835180967/4b38fb694add4ec59378324ecadd4b49/artifacts/commandr-104B-big_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/763756296835180967/851646123c0a4150938988be249ba5a3/artifacts/qwen2.5-72B-big_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/763756296835180967/50c78f11aa894e7786df46da3b05a890/artifacts/commandr-7B-small_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/763756296835180967/de923c3de24f4413a20a6eb3b6ba2a76/artifacts/qwen2.5-7B-small_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/949422143541702027/c1685999558544059bf3384188347815/artifacts/llama-8B-small_hate_taxonomies_one_shot_llm_pred.csv',
 './mlruns/949422143541702027/6d7024ce15d64f698f408f5f68b0ec3a/artifacts/mistral-7B-small_hate_taxonomies_one_shot_llm_pred.csv',
 './mlruns/529816032717002154/995d1484d0464cb2897b8ea1701ce757/artifacts/mistral-7B-small_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/529816032717002154/a158fc90640a48fd87adcf2c32af96cd/artifacts/qwen2.5-7B-small_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/529816032717002154/e24034b5591e4d3795247f4cbfc6c475/artifacts/mixtral-8x7B-small_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/529816032717002154/f300054ab578477e9543926aecdae565/artifacts/commandr-7B-small_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/529816032717002154/1f457c7d1aca447fb8c292e0ce7861fc/artifacts/qwen2.5-72B-big_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/529816032717002154/bed4838077b24457a96f0761d7beccf7/artifacts/llama-8B-small_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/529816032717002154/d1f57836592341d7bf1142aa7b767fca/artifacts/commandr-104B-big_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/529816032717002154/7fa67fe6a9cc4930a52dcc41e028a13a/artifacts/olmo-7B-small_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/529816032717002154/6b9fc2f3b96943c4925fef062a7ac144/artifacts/mixtral-8x22B-big_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/529816032717002154/38630f13f4ca43928f7839f95b0e5ae5/artifacts/olmo-7B-small_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/529816032717002154/2c21dfff23874cae87404fd5abd7e313/artifacts/llama-8B-small_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/529816032717002154/c81f652ad938401cac8dc09b2d4af57e/artifacts/mistral-7B-small_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/529816032717002154/cd696bd8a1eb420e9aaecfa5162195c0/artifacts/llama-8B-small_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/529816032717002154/e89477f022c24d4e855ba2ce01b63f9e/artifacts/commandr-104B-big_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/529816032717002154/b22d57c18a634050bef8bf13c2df816c/artifacts/qwen2.5-7B-small_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/529816032717002154/d4fa9437728e46dfb495dca826ead768/artifacts/mistral-22B-medium_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/529816032717002154/7251653543d147a490a840ebce03fd21/artifacts/mistral-22B-medium_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/529816032717002154/99f019dae80742e69a971434369103d0/artifacts/mixtral-8x22B-medium_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/529816032717002154/b90de0ee45b340c69b609a1809206038/artifacts/llama-70B-big_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/529816032717002154/31051c3dfecc49a88080c77b470b4365/artifacts/llama-70B-big_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/529816032717002154/874ee18a6d284a419800f2743b972707/artifacts/commandr-7B-small_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/529816032717002154/0c5129b92b6b4fbd97d6b5ed03d5b0e4/artifacts/mistral-22B-medium_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/529816032717002154/014277e19af4488f97128047d4d7b936/artifacts/qwen2.5-72B-big_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/529816032717002154/672f5a7d65e645b39070b4a4aeeb2a35/artifacts/commandr-7B-small_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/529816032717002154/9804734bc67745e9bfab6a3abbda4c66/artifacts/olmo2-32B-medium_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/529816032717002154/409bd7acf1b74e07908c54320ef7e0bf/artifacts/qwen2.5-7B-small_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/529816032717002154/74aa782b94554dadbac41b88e2a55e13/artifacts/olmo2-32B-medium_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/529816032717002154/7b86bb9eae5747ef94c5521e345d0ba5/artifacts/mistral-22B-medium_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/529816032717002154/40e97314513046ec80d3c564ad524ae1/artifacts/mistral-7B-small_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/529816032717002154/72d26a8e05d549269e416358c2477436/artifacts/olmo-7B-small_checkworthiness_one_shot_llm_pred.csv',
 './mlruns/851310023308608323/966468a0211f457497c66e2b3fd4b2f3/artifacts/llama-8B-small_hate_taxonomies_zero_shot_llm_pred.csv',
 './mlruns/851310023308608323/bdbd11e1f9d248818eb115151fa844fa/artifacts/mistral-7B-small_hate_taxonomies_zero_shot_llm_pred.csv',
 './mlruns/572308896497158103/39c43fb113c7476b8f8ddbf3483fff0c/artifacts/qwen2.5-7B-small_subj_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/572308896497158103/418f592baa054fd3851ac91b6e6c73a6/artifacts/mistral-7B-small_subj_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/572308896497158103/b7928cd352a742508fea38283a73f893/artifacts/commandr-104B-big_subj_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/572308896497158103/acae1ee3a52243e89b592f456eb6645a/artifacts/commandr-104B-big_subj_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/572308896497158103/08d0ed09dd0b4ac596097be3af0dee49/artifacts/olmo-7B-small_subj_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/572308896497158103/c00f0ec318104b9491b8977719e428ce/artifacts/llama-8B-small_subj_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/572308896497158103/54fedfaf20aa487da83641ca166f135e/artifacts/mistral-7B-small_subj_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/572308896497158103/7c7a7973e2aa412abb43674b95bbc89e/artifacts/qwen2.5-72B-big_subj_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/572308896497158103/1e13478b65744eb7beed0216d156ba55/artifacts/olmo-7B-small_subj_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/572308896497158103/b7c932a30c194e4483b6eb5f6a403ffa/artifacts/llama-70B-big_subj_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/572308896497158103/8c6727059f5145d6986eaea850173d55/artifacts/mistral-22B-medium_subj_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/572308896497158103/52de49203f784a70a77c0f8cc3da79af/artifacts/olmo2-32B-medium_subj_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/572308896497158103/905b573005394fd8a656936b8b41305d/artifacts/qwen2.5-7B-small_subj_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/572308896497158103/8cd4049fd6d24f4b8d2eacf57d50f9b6/artifacts/qwen2.5-7B-small_subj_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/572308896497158103/1834d27f84514b11aca4bb28e492b048/artifacts/olmo-7B-small_subj_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/572308896497158103/f44b3ea19ca64573baa952f45f89d7b2/artifacts/llama-8B-small_subj_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/572308896497158103/fc4349502e184eaea78ec786b201e64c/artifacts/commandr-7B-small_subj_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/572308896497158103/8bca4cfdc6c340a89e9f2a7b6f3a9960/artifacts/mistral-7B-small_subj_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/572308896497158103/07f4465b6ebf4c039f33718c1134fcdc/artifacts/mixtral-8x7B-small_subj_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/572308896497158103/48caff16150049dc856c0d4990b172c3/artifacts/mistral-22B-medium_subj_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/572308896497158103/d3464465315e4f29b427d7ce6a6a501d/artifacts/qwen2.5-72B-big_subj_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/572308896497158103/2184324a69ff4bc79759dba025cb5de7/artifacts/olmo2-32B-medium_subj_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/572308896497158103/503d10d400f04e18a2ccc32bebfc47cf/artifacts/mixtral-8x22B-medium_subj_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/572308896497158103/1c2d131a8ce64ebebf967151f174bce0/artifacts/commandr-7B-small_subj_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/572308896497158103/f8dec77e2e8145cabd5fbec05ea46575/artifacts/llama-8B-small_subj_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/572308896497158103/23b497c188974703a123d5384220c342/artifacts/mistral-22B-medium_subj_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/572308896497158103/2d0496f30e814729a9f511658e33c0c9/artifacts/olmo-7B-small_subj_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/572308896497158103/39ff533ffc5a43d19eb32d376fad4cac/artifacts/mixtral-8x7B-small_subj_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/572308896497158103/9cb5a15993104022b08329e7ada752d7/artifacts/mixtral-8x7B-small_subj_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/572308896497158103/f1696ca715644ee081b1ca21e7330850/artifacts/qwen2.5-7B-small_subj_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/572308896497158103/8bb93b3c04aa4018980855cb93d8d7a7/artifacts/commandr-7B-small_subj_checkworthiness_zero_shot_llm_pred.csv']

In [3]:
cworthy = [r for r in runs if ("checkworthiness" in r) and ("subj" not in r)]
htaxon = [r for r in runs if "hate_taxonomies" in r]

In [4]:
import pandas as pd


replacements = {
    "Check-worthy Factual": "CFS",
    "Non-Factual": "NFS",
    "Unimportant Factual": "UFS",
}
cols = ["premise0", "premise1", "premise2", "conclusion"]

df_orig = pd.read_csv("../data/wsf_annotations_misinformation.csv")

results = {}
for path in cworthy:
    experiment_name = path.split("/")[-1].strip(".csv")
    experiment_name = experiment_name + "_" + path.split("/")[-3]
    results[experiment_name] = {}

    # I've made some updates in the original labels :/
    df = pd.read_csv(path)
    df["check_worthy_premise0"] = df_orig["check_worthy_premise0"]
    df["check_worthy_premise1"] = df_orig["check_worthy_premise1"]
    df["check_worthy_premise2"] = df_orig["check_worthy_premise2"]
    df["check_worthy_conclusion"] = df_orig["check_worthy_conclusion"]

    df = df.rename(
        columns={
            "premise0_llm_pred": "y_pred_premise0_cw",
            "premise1_llm_pred": "y_pred_premise1_cw",
            "premise2_llm_pred": "y_pred_premise2_cw",
            "conclusion_llm_pred": "y_pred_conclusion_cw",
            "check_worthy_premise0": "y_label_premise0_cw",
            "check_worthy_premise1": "y_label_premise1_cw",
            "check_worthy_premise2": "y_label_premise2_cw",
            "check_worthy_conclusion": "y_label_conclusion_cw",
        }
    )

    df["y_pred_premise0_cw"] = df["y_pred_premise0_cw"].replace(replacements)
    df["y_pred_premise1_cw"] = df["y_pred_premise1_cw"].replace(replacements)
    df["y_pred_premise2_cw"] = df["y_pred_premise2_cw"].replace(replacements)
    df["y_pred_conclusion_cw"] = df["y_pred_conclusion_cw"].replace(replacements)

    correct_per_arg = {"args_pred": [], "args_label": [], "args_hate_label": []}
    correct_premises = {"premises_pred": [], "premises_label": [], "premises_hate_label": []}
    for c in cols:
        y_pred = df.loc[~df[c].isna(), f"y_pred_{c}_cw"].replace(replacements)
        y_label = df.loc[~df[c].isna(), f"y_label_{c}_cw"]
        y_hate_label = df.loc[~df[c].isna(), f"{c}_hate"]
        correct_per_arg["args_pred"].extend(y_pred.tolist())
        correct_per_arg["args_label"].extend(y_label.tolist())
        correct_per_arg["args_hate_label"].extend(y_hate_label.tolist())
        if c in ["premise0", "premise1", "premise2"]:
            correct_premises["premises_pred"].extend(y_pred.tolist())
            correct_premises["premises_label"].extend(y_label.tolist())
            correct_premises["premises_hate_label"].extend(y_hate_label.tolist())

        results[experiment_name][c] = (y_label == y_pred).sum() / len(y_label)

        if c in ["conclusion"]:
            results[experiment_name][f"{c}_hate"] = (y_label[y_hate_label == 1] == y_pred[y_hate_label == 1]).sum() / len(y_label[y_hate_label == 1])
            results[experiment_name][f"{c}_nohate"] = (y_label[y_hate_label == 0] == y_pred[y_hate_label == 0]).sum() / len(y_label[y_hate_label == 0])

    correct_per_arg_df = pd.DataFrame(correct_per_arg)
    correct_premises_df = pd.DataFrame(correct_premises)

    results[experiment_name]["all_premises"] = (
        (correct_premises_df["premises_pred"] == correct_premises_df["premises_label"]).sum()
    ) / len(correct_premises_df)
    
    results[experiment_name]["all_args"] = (
        (correct_per_arg_df["args_pred"] == correct_per_arg_df["args_label"]).sum()
    ) / len(correct_per_arg_df)

    nof_CFS = len(correct_per_arg_df[correct_per_arg_df["args_label"] == "CFS"])
    acc_CFS = (
        (correct_per_arg_df["args_pred"] == correct_per_arg_df["args_label"])
        & (correct_per_arg_df["args_label"] == "CFS")
    ).sum() / nof_CFS
    results[experiment_name]["all_args_CFS"] = acc_CFS

    nof_NFS = len(correct_per_arg_df[correct_per_arg_df["args_label"] == "NFS"])
    acc_NFS = (
        (correct_per_arg_df["args_pred"] == correct_per_arg_df["args_label"])
        & (correct_per_arg_df["args_label"] == "NFS")
    ).sum() / nof_NFS
    results[experiment_name]["all_args_NFS"] = acc_NFS

    nof_UFS = len(correct_per_arg_df[correct_per_arg_df["args_label"] == "UFS"])
    acc_UFS = (
        (correct_per_arg_df["args_pred"] == correct_per_arg_df["args_label"])
        & (correct_per_arg_df["args_label"] == "UFS")
    ).sum() / nof_UFS
    results[experiment_name]["all_args_UFS"] = acc_UFS

    premises_hate_df = correct_premises_df[correct_premises_df["premises_hate_label"] == 1]
    premises_nohate_df = correct_premises_df[correct_premises_df["premises_hate_label"] == 0]
    
    results[experiment_name]["all_premises_hate"] = (
        (premises_hate_df["premises_pred"] == premises_hate_df["premises_label"]).sum()
    ) / len(premises_hate_df)
    
    results[experiment_name]["all_premises_nohate"] = (
        (premises_nohate_df["premises_pred"] == premises_nohate_df["premises_label"]).sum()
    ) / len(premises_nohate_df)

In [2]:
model_order = {
    "mistral-7B-small_checkworthiness": {
        "zero-shot": ["7cff17b88ad94faa9464b2947940a2d0", "95f14e05f4de44b5bc8de54beeb797e8", "13e8d5a7a90f4df7955bd560ce954cb9"],
        "one-shot": ["995d1484d0464cb2897b8ea1701ce757", "c81f652ad938401cac8dc09b2d4af57e", "40e97314513046ec80d3c564ad524ae1"]
    },
    "llama-8B-small_checkworthiness": {
        "zero-shot": ["4d0f4bdc75d74ee6a1f69beaa5103388", "42d9ae35ca4f4d1db16008bdbfc7a9f7", "daee506eb3694b5788a3ad4dc79be07f"],
        "one-shot": ["bed4838077b24457a96f0761d7beccf7", "2c21dfff23874cae87404fd5abd7e313", "cd696bd8a1eb420e9aaecfa5162195c0"]
    },
    "olmo-7B-small_checkworthiness": {
        "zero-shot": ["3229a4dfda934fda830d0b2effb0298f", "50e85531013f40d7abf041c6ff338351", "a66c91e48b0840ed9182bd75fdebbb67"],
        "one-shot": ["7fa67fe6a9cc4930a52dcc41e028a13a", "38630f13f4ca43928f7839f95b0e5ae5", "72d26a8e05d549269e416358c2477436"],
    },
    "qwen2.5-7B-small_checkworthiness": {
        "zero-shot": ["2686e66957324dcebb68e7e14209461d", "bf33baec21b542a2a17bdced8275fa8b", "de923c3de24f4413a20a6eb3b6ba2a76"],
        "one-shot": ["a158fc90640a48fd87adcf2c32af96cd", "b22d57c18a634050bef8bf13c2df816c", "409bd7acf1b74e07908c54320ef7e0bf"]
    },
    "ommandr-7B-small_checkworthiness": {
        "zero-shot": ["2cb5a96289a54a4a84c4934163cf226b", "7e952d9fd707440ca0c36e127482cc56", "50c78f11aa894e7786df46da3b05a890"],
        "one-shot": ["f300054ab578477e9543926aecdae565", "874ee18a6d284a419800f2743b972707", "672f5a7d65e645b39070b4a4aeeb2a35"],
    },
#    "mixtral-8x7B-small_checkworthiness": {
#        "zero-shot": ["42718aa5c1734282b1d5f86be12abed3"],
#        "one-shot": ["e24034b5591e4d3795247f4cbfc6c475"]
#    },
    "mistral-22B-medium_checkworthiness": {
        "zero-shot": ["d8c0afbd8c6b461496d8e323aea7d846", "d3c2a2ee237648b58324fc4cfc87346a", "dd527efae34c42ab82196cc6f0da9595"],
        "one-shot": ["7251653543d147a490a840ebce03fd21", "0c5129b92b6b4fbd97d6b5ed03d5b0e4", "7b86bb9eae5747ef94c5521e345d0ba5"]
    },
#    "olmo2-32B-medium_checkworthiness": {
#        "zero-shot": ["22493e1f462142fc8b671e105e706036", "31589a761eff46f29f25be22e615ea84"],
#        "one-shot": ["9804734bc67745e9bfab6a3abbda4c66", "74aa782b94554dadbac41b88e2a55e13"]
#    },
#    "mixtral-8x22B-medium_checkworthiness": {
#        "zero-shot": ["ea51bb6edb6c4e79aa215663adb22c13", "255fd733ab3641e19f95c1823ef5923c"],
#        "one-shot": ["6b9fc2f3b96943c4925fef062a7ac144", "99f019dae80742e69a971434369103d0"]
#    },
#    "llama-70B-big_checkworthiness": {
#        "zero-shot": ["ce0707c1e3a0426fbe226774ceac01f7", "c9dcabb0dbde4746b2dfe72c56d24245"],
#        "one-shot": ["b90de0ee45b340c69b609a1809206038", "31051c3dfecc49a88080c77b470b4365"],
#    },
#    "qwen2.5-72B-big_checkworthiness": {
#        "zero-shot": ["e6ca32e4ac724205aeca7c9f7d5ac015", "851646123c0a4150938988be249ba5a3"],
#        "one-shot": ["1f457c7d1aca447fb8c292e0ce7861fc", "014277e19af4488f97128047d4d7b936"]
#    },
#    "ommandr-104B-big_checkworthiness": {
#        "zero-shot": ["99977df7b2044889b1c188ea7941ae5f", "4b38fb694add4ec59378324ecadd4b49"],
#        "one-shot": ["d1f57836592341d7bf1142aa7b767fca", "e89477f022c24d4e855ba2ce01b63f9e"]
#    }
}


# Transform the dictionary
new_model_order = {}

for model_name, data in model_order.items():
    new_model_order[model_name] = {}
    for shot_type, ids in data.items():
        new_urls = []
        for id_ in ids:
            # Find URL containing this id
            matches = [u for u in runs if id_ in u]
            if len(matches) != 1:
                raise ValueError(f"Expected exactly one URL for ID {id_}, found {len(matches)}")
            new_urls.append(matches[0])
        new_model_order[model_name][shot_type] = new_urls

# new_model_order now has URLs instead of IDs
print(new_model_order)

{'mistral-7B-small_checkworthiness': {'zero-shot': ['./mlruns/763756296835180967/7cff17b88ad94faa9464b2947940a2d0/artifacts/mistral-7B-small_checkworthiness_zero_shot_llm_pred.csv', './mlruns/763756296835180967/95f14e05f4de44b5bc8de54beeb797e8/artifacts/mistral-7B-small_checkworthiness_zero_shot_llm_pred.csv', './mlruns/763756296835180967/13e8d5a7a90f4df7955bd560ce954cb9/artifacts/mistral-7B-small_checkworthiness_zero_shot_llm_pred.csv'], 'one-shot': ['./mlruns/529816032717002154/995d1484d0464cb2897b8ea1701ce757/artifacts/mistral-7B-small_checkworthiness_one_shot_llm_pred.csv', './mlruns/529816032717002154/c81f652ad938401cac8dc09b2d4af57e/artifacts/mistral-7B-small_checkworthiness_one_shot_llm_pred.csv', './mlruns/529816032717002154/40e97314513046ec80d3c564ad524ae1/artifacts/mistral-7B-small_checkworthiness_one_shot_llm_pred.csv']}, 'llama-8B-small_checkworthiness': {'zero-shot': ['./mlruns/763756296835180967/4d0f4bdc75d74ee6a1f69beaa5103388/artifacts/llama-8B-small_checkworthiness_zero_shot_llm_pred.csv', './mlruns/763756296835180967/42d9ae35ca4f4d1db16008bdbfc7a9f7/artifacts/llama-8B-small_checkworthiness_zero_shot_llm_pred.csv', './mlruns/763756296835180967/daee506eb3694b5788a3ad4dc79be07f/artifacts/llama-8B-small_checkworthiness_zero_shot_llm_pred.csv'], 'one-shot': ['./mlruns/529816032717002154/bed4838077b24457a96f0761d7beccf7/artifacts/llama-8B-small_checkworthiness_one_shot_llm_pred.csv', './mlruns/529816032717002154/2c21dfff23874cae87404fd5abd7e313/artifacts/llama-8B-small_checkworthiness_one_shot_llm_pred.csv', './mlruns/529816032717002154/cd696bd8a1eb420e9aaecfa5162195c0/artifacts/llama-8B-small_checkworthiness_one_shot_llm_pred.csv']}, 'olmo-7B-small_checkworthiness': {'zero-shot': ['./mlruns/763756296835180967/3229a4dfda934fda830d0b2effb0298f/artifacts/olmo-7B-small_checkworthiness_zero_shot_llm_pred.csv', './mlruns/763756296835180967/50e85531013f40d7abf041c6ff338351/artifacts/olmo-7B-small_checkworthiness_zero_shot_llm_pred.csv', './mlruns/763756296835180967/a66c91e48b0840ed9182bd75fdebbb67/artifacts/olmo-7B-small_checkworthiness_zero_shot_llm_pred.csv'], 'one-shot': ['./mlruns/529816032717002154/7fa67fe6a9cc4930a52dcc41e028a13a/artifacts/olmo-7B-small_checkworthiness_one_shot_llm_pred.csv', './mlruns/529816032717002154/38630f13f4ca43928f7839f95b0e5ae5/artifacts/olmo-7B-small_checkworthiness_one_shot_llm_pred.csv', './mlruns/529816032717002154/72d26a8e05d549269e416358c2477436/artifacts/olmo-7B-small_checkworthiness_one_shot_llm_pred.csv']}, 'qwen2.5-7B-small_checkworthiness': {'zero-shot': ['./mlruns/763756296835180967/2686e66957324dcebb68e7e14209461d/artifacts/qwen2.5-7B-small_checkworthiness_zero_shot_llm_pred.csv', './mlruns/763756296835180967/bf33baec21b542a2a17bdced8275fa8b/artifacts/qwen2.5-7B-small_checkworthiness_zero_shot_llm_pred.csv', './mlruns/763756296835180967/de923c3de24f4413a20a6eb3b6ba2a76/artifacts/qwen2.5-7B-small_checkworthiness_zero_shot_llm_pred.csv'], 'one-shot': ['./mlruns/529816032717002154/a158fc90640a48fd87adcf2c32af96cd/artifacts/qwen2.5-7B-small_checkworthiness_one_shot_llm_pred.csv', './mlruns/529816032717002154/b22d57c18a634050bef8bf13c2df816c/artifacts/qwen2.5-7B-small_checkworthiness_one_shot_llm_pred.csv', './mlruns/529816032717002154/409bd7acf1b74e07908c54320ef7e0bf/artifacts/qwen2.5-7B-small_checkworthiness_one_shot_llm_pred.csv']}, 'ommandr-7B-small_checkworthiness': {'zero-shot': ['./mlruns/763756296835180967/2cb5a96289a54a4a84c4934163cf226b/artifacts/commandr-7B-small_checkworthiness_zero_shot_llm_pred.csv', './mlruns/763756296835180967/7e952d9fd707440ca0c36e127482cc56/artifacts/commandr-7B-small_checkworthiness_zero_shot_llm_pred.csv', './mlruns/763756296835180967/50c78f11aa894e7786df46da3b05a890/artifacts/commandr-7B-small_checkworthiness_zero_shot_llm_pred.csv'], 'one-shot': ['./mlruns/529816032717002154/f300054ab578477e9543926aecdae565/artifacts/commandr-7B-small_checkworthiness_one_shot_llm_pred.csv', './mlruns/529816032717002154/874ee18a6d284a419800f2743b972707/artifacts/commandr-7B-small_checkworthiness_one_shot_llm_pred.csv', './mlruns/529816032717002154/672f5a7d65e645b39070b4a4aeeb2a35/artifacts/commandr-7B-small_checkworthiness_one_shot_llm_pred.csv']}, 'mistral-22B-medium_checkworthiness': {'zero-shot': ['./mlruns/763756296835180967/d8c0afbd8c6b461496d8e323aea7d846/artifacts/mistral-22B-medium_checkworthiness_zero_shot_llm_pred.csv', './mlruns/763756296835180967/d3c2a2ee237648b58324fc4cfc87346a/artifacts/mistral-22B-medium_checkworthiness_zero_shot_llm_pred.csv', './mlruns/763756296835180967/dd527efae34c42ab82196cc6f0da9595/artifacts/mistral-22B-medium_checkworthiness_zero_shot_llm_pred.csv'], 'one-shot': ['./mlruns/529816032717002154/7251653543d147a490a840ebce03fd21/artifacts/mistral-22B-medium_checkworthiness_one_shot_llm_pred.csv', './mlruns/529816032717002154/0c5129b92b6b4fbd97d6b5ed03d5b0e4/artifacts/mistral-22B-medium_checkworthiness_one_shot_llm_pred.csv', './mlruns/529816032717002154/7b86bb9eae5747ef94c5521e345d0ba5/artifacts/mistral-22B-medium_checkworthiness_one_shot_llm_pred.csv']}}

In [3]:
from collections import Counter


def majority_vote(row, col):
    values = [row[f"{col}_m0"], row[f"{col}_m1"], row[f"{col}_m2"]]
    counts = Counter(values)
    most_common_value, count = counts.most_common(1)[0]
    if count >= 2:
        return pd.Series({col: most_common_value, f"{col}_agreement_count": count})
    else:
        return pd.Series({col: "All unequal", f"{col}_agreement_count": 1})

runs_w_paths = []
for model_name, data in new_model_order.items():
    for shot_type, urls in data.items():
        df0, df1, df2 = pd.read_csv(urls[0]), pd.read_csv(urls[1]), pd.read_csv(urls[2])
        new_df = df0.copy()
        new_df = new_df.drop(
            columns=["premise0_llm_pred", "premise1_llm_pred", "premise2_llm_pred"]
        )

        new_df["premise0_llm_pred_m0"] = df0["premise0_llm_pred"]
        new_df["premise0_llm_pred_m1"] = df1["premise0_llm_pred"]
        new_df["premise0_llm_pred_m2"] = df2["premise0_llm_pred"]
        new_df[["premise0_llm_pred", "agreement_count"]] = new_df.apply(
            lambda row: majority_vote(row, col="premise0_llm_pred"), axis=1
        )

        new_df["premise1_llm_pred_m0"] = df0["premise1_llm_pred"]
        new_df["premise1_llm_pred_m1"] = df1["premise1_llm_pred"]
        new_df["premise1_llm_pred_m2"] = df2["premise1_llm_pred"]
        new_df[["premise1_llm_pred", "agreement_count"]] = new_df.apply(
            lambda row: majority_vote(row, col="premise1_llm_pred"), axis=1
        )

        new_df["premise2_llm_pred_m0"] = df0["premise2_llm_pred"]
        new_df["premise2_llm_pred_m1"] = df1["premise2_llm_pred"]
        new_df["premise2_llm_pred_m2"] = df2["premise2_llm_pred"]
        new_df[["premise2_llm_pred", "agreement_count"]] = new_df.apply(
            lambda row: majority_vote(row, col="premise2_llm_pred"), axis=1
        )

        new_df["conclusion_llm_pred_m0"] = df0["conclusion_llm_pred"]
        new_df["conclusion_llm_pred_m1"] = df1["conclusion_llm_pred"]
        new_df["conclusion_llm_pred_m2"] = df2["conclusion_llm_pred"]
        new_df[["conclusion_llm_pred", "agreement_count"]] = new_df.apply(
            lambda row: majority_vote(row, col="conclusion_llm_pred"), axis=1
        )
        runs_w_paths.append((new_df, urls))

In [6]:
import pandas as pd


replacements = {
    "Check-worthy Factual": "CFS",
    "Non-Factual": "NFS",
    "Unimportant Factual": "UFS",
}
cols = ["premise0", "premise1", "premise2", "conclusion"]

df_orig = pd.read_csv("../data/wsf_annotations_misinformation.csv")

results = {}
for df, path in runs_w_paths:
    experiment_name = path[0].split("/")[-1].strip(".csv")
    experiment_name = experiment_name # + "_" + path.split("/")[-3]
    results[experiment_name] = {}

    df["check_worthy_premise0"] = df_orig["check_worthy_premise0"]
    df["check_worthy_premise1"] = df_orig["check_worthy_premise1"]
    df["check_worthy_premise2"] = df_orig["check_worthy_premise2"]
    df["check_worthy_conclusion"] = df_orig["check_worthy_conclusion"]

    df = df.rename(
        columns={
            "premise0_llm_pred": "y_pred_premise0_cw",
            "premise1_llm_pred": "y_pred_premise1_cw",
            "premise2_llm_pred": "y_pred_premise2_cw",
            "conclusion_llm_pred": "y_pred_conclusion_cw",
            "check_worthy_premise0": "y_label_premise0_cw",
            "check_worthy_premise1": "y_label_premise1_cw",
            "check_worthy_premise2": "y_label_premise2_cw",
            "check_worthy_conclusion": "y_label_conclusion_cw",
        }
    )

    df["y_pred_premise0_cw"] = df["y_pred_premise0_cw"].replace(replacements)
    df["y_pred_premise1_cw"] = df["y_pred_premise1_cw"].replace(replacements)
    df["y_pred_premise2_cw"] = df["y_pred_premise2_cw"].replace(replacements)
    df["y_pred_conclusion_cw"] = df["y_pred_conclusion_cw"].replace(replacements)

    correct_per_arg = {"args_pred": [], "args_label": [], "args_hate_label": []}
    correct_premises = {"premises_pred": [], "premises_label": [], "premises_hate_label": []}
    for c in cols:
        y_pred = df.loc[~df[c].isna(), f"y_pred_{c}_cw"].replace(replacements)
        y_label = df.loc[~df[c].isna(), f"y_label_{c}_cw"]
        y_hate_label = df.loc[~df[c].isna(), f"{c}_hate"]
        correct_per_arg["args_pred"].extend(y_pred.tolist())
        correct_per_arg["args_label"].extend(y_label.tolist())
        correct_per_arg["args_hate_label"].extend(y_hate_label.tolist())
        if c in ["premise0", "premise1", "premise2"]:
            correct_premises["premises_pred"].extend(y_pred.tolist())
            correct_premises["premises_label"].extend(y_label.tolist())
            correct_premises["premises_hate_label"].extend(y_hate_label.tolist())

        results[experiment_name][c] = (y_label == y_pred).sum() / len(y_label)

        if c in ["conclusion"]:
            results[experiment_name][f"{c}_hate"] = (y_label[y_hate_label == 1] == y_pred[y_hate_label == 1]).sum() / len(y_label[y_hate_label == 1])
            results[experiment_name][f"{c}_nohate"] = (y_label[y_hate_label == 0] == y_pred[y_hate_label == 0]).sum() / len(y_label[y_hate_label == 0])

    correct_per_arg_df = pd.DataFrame(correct_per_arg)
    correct_premises_df = pd.DataFrame(correct_premises)

    results[experiment_name]["all_premises"] = (
        (correct_premises_df["premises_pred"] == correct_premises_df["premises_label"]).sum()
    ) / len(correct_premises_df)
    
    results[experiment_name]["all_args"] = (
        (correct_per_arg_df["args_pred"] == correct_per_arg_df["args_label"]).sum()
    ) / len(correct_per_arg_df)

    nof_CFS = len(correct_per_arg_df[correct_per_arg_df["args_label"] == "CFS"])
    acc_CFS = (
        (correct_per_arg_df["args_pred"] == correct_per_arg_df["args_label"])
        & (correct_per_arg_df["args_label"] == "CFS")
    ).sum() / nof_CFS
    results[experiment_name]["all_args_CFS"] = acc_CFS

    nof_NFS = len(correct_per_arg_df[correct_per_arg_df["args_label"] == "NFS"])
    acc_NFS = (
        (correct_per_arg_df["args_pred"] == correct_per_arg_df["args_label"])
        & (correct_per_arg_df["args_label"] == "NFS")
    ).sum() / nof_NFS
    results[experiment_name]["all_args_NFS"] = acc_NFS

    nof_UFS = len(correct_per_arg_df[correct_per_arg_df["args_label"] == "UFS"])
    acc_UFS = (
        (correct_per_arg_df["args_pred"] == correct_per_arg_df["args_label"])
        & (correct_per_arg_df["args_label"] == "UFS")
    ).sum() / nof_UFS
    results[experiment_name]["all_args_UFS"] = acc_UFS

    premises_hate_df = correct_premises_df[correct_premises_df["premises_hate_label"] == 1]
    premises_nohate_df = correct_premises_df[correct_premises_df["premises_hate_label"] == 0]
    
    results[experiment_name]["all_premises_hate"] = (
        (premises_hate_df["premises_pred"] == premises_hate_df["premises_label"]).sum()
    ) / len(premises_hate_df)
    
    results[experiment_name]["all_premises_nohate"] = (
        (premises_nohate_df["premises_pred"] == premises_nohate_df["premises_label"]).sum()
    ) / len(premises_nohate_df)

In [7]:
df_results = pd.DataFrame(results).transpose()

In [9]:
df_results[["premise0", "premise1", "premise2", "all_premises", "conclusion", "all_args", "all_args_CFS", "all_args_NFS", "all_args_UFS", "all_premises_hate", "all_premises_nohate", "conclusion_hate", "conclusion_nohate"]]

,premise0,premise1,premise2,all_premises,conclusion,all_args,all_args_CFS,all_args_NFS,all_args_UFS,all_premises_hate,all_premises_nohate,conclusion_hate,conclusion_nohate
mistral-7B-small_checkworthiness_zero_shot_llm_pred,0.261062,0.278146,0.275862,0.268473,0.484581,0.345972,0.095890,0.993939,0.196078,0.197970,0.334928,0.449704,0.586207
mistral-7B-small_checkworthiness_one_shot_llm_pred,0.389381,0.350993,0.241379,0.364532,0.484581,0.407583,0.219178,0.806061,0.441176,0.269036,0.454545,0.461538,0.551724
llama-8B-small_checkworthiness_zero_shot_llm_pred,0.194690,0.218543,0.206897,0.204433,0.449339,0.292259,0.027397,0.987879,0.117647,0.192893,0.215311,0.426036,0.517241
llama-8B-small_checkworthiness_one_shot_llm_pred,0.225664,0.238411,0.310345,0.236453,0.480176,0.323855,0.082192,0.963636,0.156863,0.213198,0.258373,0.455621,0.551724
olmo-7B-small_checkworthiness_zero_shot_llm_pred,0.371681,0.331126,0.310345,0.352217,0.453744,0.388626,0.213699,0.854545,0.264706,0.269036,0.430622,0.437870,0.500000
olmo-7B-small_checkworthiness_one_shot_llm_pred,0.252212,0.211921,0.275862,0.238916,0.471366,0.322275,0.090411,0.963636,0.117647,0.208122,0.267943,0.449704,0.534483
qwen2.5-7B-small_checkworthiness_zero_shot_llm_pred,0.296460,0.284768,0.241379,0.288177,0.497797,0.363349,0.104110,0.963636,0.323529,0.243655,0.330144,0.473373,0.568966
qwen2.5-7B-small_checkworthiness_one_shot_llm_pred,0.243363,0.225166,0.206897,0.233990,0.449339,0.311216,0.054795,0.993939,0.127451,0.213198,0.253589,0.431953,0.500000
ommandr-7B-small_checkworthiness_zero_shot_llm_pred,0.424779,0.350993,0.379310,0.394089,0.572687,0.458136,0.419178,0.800000,0.049020,0.411168,0.377990,0.573964,0.568966
ommandr-7B-small_checkworthiness_one_shot_llm_pred,0.371681,0.350993,0.310345,0.359606,0.537445,0.423381,0.339726,0.854545,0.029412,0.375635,0.344498,0.532544,0.551724
mistral-22B-medium_checkworthiness_zero_shot_llm_pred,0.265487,0.211921,0.275862,0.246305,0.497797,0.336493,0.123288,0.987879,0.049020,0.223350,0.267943,0.479290,0.551724
mistral-22B-medium_checkworthiness_one_shot_llm_pred,0.212389,0.205298,0.206897,0.209360,0.471366,0.303318,0.063014,1.000000,0.039216,0.197970,0.220096,0.455621,0.517241

In [5]:
path

['./mlruns/763756296835180967/7cff17b88ad94faa9464b2947940a2d0/artifacts/mistral-7B-small_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/763756296835180967/95f14e05f4de44b5bc8de54beeb797e8/artifacts/mistral-7B-small_checkworthiness_zero_shot_llm_pred.csv',
 './mlruns/763756296835180967/13e8d5a7a90f4df7955bd560ce954cb9/artifacts/mistral-7B-small_checkworthiness_zero_shot_llm_pred.csv']

In [44]:
new_model_order

{'mistral-7B-small_checkworthiness': {'zero-shot': ['./mlruns/763756296835180967/7cff17b88ad94faa9464b2947940a2d0/artifacts/mistral-7B-small_checkworthiness_zero_shot_llm_pred.csv',
   './mlruns/763756296835180967/95f14e05f4de44b5bc8de54beeb797e8/artifacts/mistral-7B-small_checkworthiness_zero_shot_llm_pred.csv',
   './mlruns/763756296835180967/13e8d5a7a90f4df7955bd560ce954cb9/artifacts/mistral-7B-small_checkworthiness_zero_shot_llm_pred.csv'],
  'one-shot': ['./mlruns/529816032717002154/995d1484d0464cb2897b8ea1701ce757/artifacts/mistral-7B-small_checkworthiness_one_shot_llm_pred.csv',
   './mlruns/529816032717002154/c81f652ad938401cac8dc09b2d4af57e/artifacts/mistral-7B-small_checkworthiness_one_shot_llm_pred.csv',
   './mlruns/529816032717002154/40e97314513046ec80d3c564ad524ae1/artifacts/mistral-7B-small_checkworthiness_one_shot_llm_pred.csv']},
 'llama-8B-small_checkworthiness': {'zero-shot': ['./mlruns/763756296835180967/4d0f4bdc75d74ee6a1f69beaa5103388/artifacts/llama-8B-small_checkworthiness_zero_shot_llm_pred.csv',
   './mlruns/763756296835180967/42d9ae35ca4f4d1db16008bdbfc7a9f7/artifacts/llama-8B-small_checkworthiness_zero_shot_llm_pred.csv',
   './mlruns/763756296835180967/daee506eb3694b5788a3ad4dc79be07f/artifacts/llama-8B-small_checkworthiness_zero_shot_llm_pred.csv'],
  'one-shot': ['./mlruns/529816032717002154/bed4838077b24457a96f0761d7beccf7/artifacts/llama-8B-small_checkworthiness_one_shot_llm_pred.csv',
   './mlruns/529816032717002154/2c21dfff23874cae87404fd5abd7e313/artifacts/llama-8B-small_checkworthiness_one_shot_llm_pred.csv',
   './mlruns/529816032717002154/cd696bd8a1eb420e9aaecfa5162195c0/artifacts/llama-8B-small_checkworthiness_one_shot_llm_pred.csv']},
 'olmo-7B-small_checkworthiness': {'zero-shot': ['./mlruns/763756296835180967/3229a4dfda934fda830d0b2effb0298f/artifacts/olmo-7B-small_checkworthiness_zero_shot_llm_pred.csv',
   './mlruns/763756296835180967/50e85531013f40d7abf041c6ff338351/artifacts/olmo-7B-small_checkworthiness_zero_shot_llm_pred.csv',
   './mlruns/763756296835180967/a66c91e48b0840ed9182bd75fdebbb67/artifacts/olmo-7B-small_checkworthiness_zero_shot_llm_pred.csv'],
  'one-shot': ['./mlruns/529816032717002154/7fa67fe6a9cc4930a52dcc41e028a13a/artifacts/olmo-7B-small_checkworthiness_one_shot_llm_pred.csv',
   './mlruns/529816032717002154/38630f13f4ca43928f7839f95b0e5ae5/artifacts/olmo-7B-small_checkworthiness_one_shot_llm_pred.csv',
   './mlruns/529816032717002154/72d26a8e05d549269e416358c2477436/artifacts/olmo-7B-small_checkworthiness_one_shot_llm_pred.csv']},
 'qwen2.5-7B-small_checkworthiness': {'zero-shot': ['./mlruns/763756296835180967/2686e66957324dcebb68e7e14209461d/artifacts/qwen2.5-7B-small_checkworthiness_zero_shot_llm_pred.csv',
   './mlruns/763756296835180967/bf33baec21b542a2a17bdced8275fa8b/artifacts/qwen2.5-7B-small_checkworthiness_zero_shot_llm_pred.csv',
   './mlruns/763756296835180967/de923c3de24f4413a20a6eb3b6ba2a76/artifacts/qwen2.5-7B-small_checkworthiness_zero_shot_llm_pred.csv'],
  'one-shot': ['./mlruns/529816032717002154/a158fc90640a48fd87adcf2c32af96cd/artifacts/qwen2.5-7B-small_checkworthiness_one_shot_llm_pred.csv',
   './mlruns/529816032717002154/b22d57c18a634050bef8bf13c2df816c/artifacts/qwen2.5-7B-small_checkworthiness_one_shot_llm_pred.csv',
   './mlruns/529816032717002154/409bd7acf1b74e07908c54320ef7e0bf/artifacts/qwen2.5-7B-small_checkworthiness_one_shot_llm_pred.csv']},
 'ommandr-7B-small_checkworthiness': {'zero-shot': ['./mlruns/763756296835180967/2cb5a96289a54a4a84c4934163cf226b/artifacts/commandr-7B-small_checkworthiness_zero_shot_llm_pred.csv',
   './mlruns/763756296835180967/7e952d9fd707440ca0c36e127482cc56/artifacts/commandr-7B-small_checkworthiness_zero_shot_llm_pred.csv',
   './mlruns/763756296835180967/50c78f11aa894e7786df46da3b05a890/artifacts/commandr-7B-small_checkworthiness_zero_shot_llm_pred.csv'],
  'one-shot': ['./mlruns/529816032717002154/f300054ab578477e9543926aecdae565/artifacts/commandr-7B-small_checkworthiness_one_shot_llm_pred.csv',
   './mlruns/529816032717002154/874ee18a6d284a419800f2743b972707/artifacts/commandr-7B-small_checkworthiness_one_shot_llm_pred.csv',
   './mlruns/529816032717002154/672f5a7d65e645b39070b4a4aeeb2a35/artifacts/commandr-7B-small_checkworthiness_one_shot_llm_pred.csv']},
 'mixtral-8x7B-small_checkworthiness': {'zero-shot': ['./mlruns/763756296835180967/42718aa5c1734282b1d5f86be12abed3/artifacts/mixtral-8x7B-small_checkworthiness_zero_shot_llm_pred.csv'],
  'one-shot': ['./mlruns/529816032717002154/e24034b5591e4d3795247f4cbfc6c475/artifacts/mixtral-8x7B-small_checkworthiness_one_shot_llm_pred.csv']},
 'mistral-22B-medium_checkworthiness': {'zero-shot': ['./mlruns/763756296835180967/d8c0afbd8c6b461496d8e323aea7d846/artifacts/mistral-22B-medium_checkworthiness_zero_shot_llm_pred.csv',
   './mlruns/763756296835180967/d3c2a2ee237648b58324fc4cfc87346a/artifacts/mistral-22B-medium_checkworthiness_zero_shot_llm_pred.csv',
   './mlruns/763756296835180967/dd527efae34c42ab82196cc6f0da9595/artifacts/mistral-22B-medium_checkworthiness_zero_shot_llm_pred.csv'],
  'one-shot': ['./mlruns/529816032717002154/7251653543d147a490a840ebce03fd21/artifacts/mistral-22B-medium_checkworthiness_one_shot_llm_pred.csv',
   './mlruns/529816032717002154/0c5129b92b6b4fbd97d6b5ed03d5b0e4/artifacts/mistral-22B-medium_checkworthiness_one_shot_llm_pred.csv',
   './mlruns/529816032717002154/7b86bb9eae5747ef94c5521e345d0ba5/artifacts/mistral-22B-medium_checkworthiness_one_shot_llm_pred.csv']},
 'olmo2-32B-medium_checkworthiness': {'zero-shot': ['./mlruns/763756296835180967/22493e1f462142fc8b671e105e706036/artifacts/olmo2-32B-medium_checkworthiness_zero_shot_llm_pred.csv',
   './mlruns/763756296835180967/31589a761eff46f29f25be22e615ea84/artifacts/olmo2-32B-medium_checkworthiness_zero_shot_llm_pred.csv'],
  'one-shot': ['./mlruns/529816032717002154/9804734bc67745e9bfab6a3abbda4c66/artifacts/olmo2-32B-medium_checkworthiness_one_shot_llm_pred.csv',
   './mlruns/529816032717002154/74aa782b94554dadbac41b88e2a55e13/artifacts/olmo2-32B-medium_checkworthiness_one_shot_llm_pred.csv']},
 'mixtral-8x22B-medium_checkworthiness': {'zero-shot': ['./mlruns/763756296835180967/ea51bb6edb6c4e79aa215663adb22c13/artifacts/mixtral-8x22B-medium_checkworthiness_zero_shot_llm_pred.csv',
   './mlruns/763756296835180967/255fd733ab3641e19f95c1823ef5923c/artifacts/mixtral-8x22B-big_checkworthiness_zero_shot_llm_pred.csv'],
  'one-shot': ['./mlruns/529816032717002154/6b9fc2f3b96943c4925fef062a7ac144/artifacts/mixtral-8x22B-big_checkworthiness_one_shot_llm_pred.csv',
   './mlruns/529816032717002154/99f019dae80742e69a971434369103d0/artifacts/mixtral-8x22B-medium_checkworthiness_one_shot_llm_pred.csv']},
 'llama-70B-big_checkworthiness': {'zero-shot': ['./mlruns/763756296835180967/ce0707c1e3a0426fbe226774ceac01f7/artifacts/llama-70B-big_checkworthiness_zero_shot_llm_pred.csv',
   './mlruns/763756296835180967/c9dcabb0dbde4746b2dfe72c56d24245/artifacts/llama-70B-big_checkworthiness_zero_shot_llm_pred.csv'],
  'one-shot': ['./mlruns/529816032717002154/b90de0ee45b340c69b609a1809206038/artifacts/llama-70B-big_checkworthiness_one_shot_llm_pred.csv',
   './mlruns/529816032717002154/31051c3dfecc49a88080c77b470b4365/artifacts/llama-70B-big_checkworthiness_one_shot_llm_pred.csv']},
 'qwen2.5-72B-big_checkworthiness': {'zero-shot': ['./mlruns/763756296835180967/e6ca32e4ac724205aeca7c9f7d5ac015/artifacts/qwen2.5-72B-big_checkworthiness_zero_shot_llm_pred.csv',
   './mlruns/763756296835180967/851646123c0a4150938988be249ba5a3/artifacts/qwen2.5-72B-big_checkworthiness_zero_shot_llm_pred.csv'],
  'one-shot': ['./mlruns/529816032717002154/1f457c7d1aca447fb8c292e0ce7861fc/artifacts/qwen2.5-72B-big_checkworthiness_one_shot_llm_pred.csv',
   './mlruns/529816032717002154/014277e19af4488f97128047d4d7b936/artifacts/qwen2.5-72B-big_checkworthiness_one_shot_llm_pred.csv']},
 'ommandr-104B-big_checkworthiness': {'zero-shot': ['./mlruns/763756296835180967/99977df7b2044889b1c188ea7941ae5f/artifacts/commandr-104B-big_checkworthiness_zero_shot_llm_pred.csv',
   './mlruns/763756296835180967/4b38fb694add4ec59378324ecadd4b49/artifacts/commandr-104B-big_checkworthiness_zero_shot_llm_pred.csv'],
  'one-shot': ['./mlruns/529816032717002154/d1f57836592341d7bf1142aa7b767fca/artifacts/commandr-104B-big_checkworthiness_one_shot_llm_pred.csv',
   './mlruns/529816032717002154/e89477f022c24d4e855ba2ce01b63f9e/artifacts/commandr-104B-big_checkworthiness_one_shot_llm_pred.csv']}}

In [ ]:
relevant_runs_dfs = []
for path in cworthy:
    experiment_name = path.split("/")[-1].strip(".csv")
    experiment_name = experiment_name + "_" + path.split("/")[-3]
    df = pd.read_csv(path)
    relevant_runs_dfs.append(df)

In [5]:
model_order = {
    "mistral-7B-small_checkworthiness": {
        "zero-shot": ["7cff17b88ad94faa9464b2947940a2d0", "95f14e05f4de44b5bc8de54beeb797e8", "13e8d5a7a90f4df7955bd560ce954cb9"],
        "one-shot": ["995d1484d0464cb2897b8ea1701ce757", "c81f652ad938401cac8dc09b2d4af57e", "40e97314513046ec80d3c564ad524ae1"]
    },
    "llama-8B-small_checkworthiness": {
        "zero-shot": ["4d0f4bdc75d74ee6a1f69beaa5103388", "42d9ae35ca4f4d1db16008bdbfc7a9f7", "daee506eb3694b5788a3ad4dc79be07f"],
        "one-shot": ["bed4838077b24457a96f0761d7beccf7", "2c21dfff23874cae87404fd5abd7e313", "cd696bd8a1eb420e9aaecfa5162195c0"]
    },
    "olmo-7B-small_checkworthiness": {
        "zero-shot": ["3229a4dfda934fda830d0b2effb0298f", "50e85531013f40d7abf041c6ff338351", "a66c91e48b0840ed9182bd75fdebbb67"],
        "one-shot": ["7fa67fe6a9cc4930a52dcc41e028a13a", "38630f13f4ca43928f7839f95b0e5ae5", "72d26a8e05d549269e416358c2477436"],
    },
    "qwen2.5-7B-small_checkworthiness": {
        "zero-shot": ["2686e66957324dcebb68e7e14209461d", "bf33baec21b542a2a17bdced8275fa8b", "de923c3de24f4413a20a6eb3b6ba2a76"],
        "one-shot": ["a158fc90640a48fd87adcf2c32af96cd", "b22d57c18a634050bef8bf13c2df816c", "409bd7acf1b74e07908c54320ef7e0bf"]
    },
    "ommandr-7B-small_checkworthiness": {
        "zero-shot": ["2cb5a96289a54a4a84c4934163cf226b", "7e952d9fd707440ca0c36e127482cc56", "50c78f11aa894e7786df46da3b05a890"],
        "one-shot": ["f300054ab578477e9543926aecdae565", "874ee18a6d284a419800f2743b972707", "672f5a7d65e645b39070b4a4aeeb2a35"],
    },
    "mixtral-8x7B-small_checkworthiness": {
        "zero-shot": ["42718aa5c1734282b1d5f86be12abed3"],
        "one-shot": ["e24034b5591e4d3795247f4cbfc6c475"]
    },
    "mistral-22B-medium_checkworthiness": {
        "zero-shot": ["d8c0afbd8c6b461496d8e323aea7d846", "d3c2a2ee237648b58324fc4cfc87346a", "dd527efae34c42ab82196cc6f0da9595"],
        "one-shot": ["7251653543d147a490a840ebce03fd21", "0c5129b92b6b4fbd97d6b5ed03d5b0e4", "7b86bb9eae5747ef94c5521e345d0ba5"]
    },
    "olmo2-32B-medium_checkworthiness": {
        "zero-shot": ["22493e1f462142fc8b671e105e706036", "31589a761eff46f29f25be22e615ea84"],
        "one-shot": ["9804734bc67745e9bfab6a3abbda4c66", "74aa782b94554dadbac41b88e2a55e13"]
    },
    "mixtral-8x22B-medium_checkworthiness": {
        "zero-shot": ["ea51bb6edb6c4e79aa215663adb22c13", "255fd733ab3641e19f95c1823ef5923c"],
        "one-shot": ["6b9fc2f3b96943c4925fef062a7ac144", "99f019dae80742e69a971434369103d0"]
    },
    "llama-70B-big_checkworthiness": {
        "zero-shot": ["ce0707c1e3a0426fbe226774ceac01f7", "c9dcabb0dbde4746b2dfe72c56d24245"],
        "one-shot": ["b90de0ee45b340c69b609a1809206038", "31051c3dfecc49a88080c77b470b4365"],
    },
    "qwen2.5-72B-big_checkworthiness": {
        "zero-shot": ["e6ca32e4ac724205aeca7c9f7d5ac015", "851646123c0a4150938988be249ba5a3"],
        "one-shot": ["1f457c7d1aca447fb8c292e0ce7861fc", "014277e19af4488f97128047d4d7b936"]
    },
    "ommandr-104B-big_checkworthiness": {
        "zero-shot": ["99977df7b2044889b1c188ea7941ae5f", "4b38fb694add4ec59378324ecadd4b49"],
        "one-shot": ["d1f57836592341d7bf1142aa7b767fca", "e89477f022c24d4e855ba2ce01b63f9e"]
    }
}

# --- Build the full desired order list ---
desired_order = []

for model, shots in model_order.items():
    for shot_type in ["zero-shot", "one-shot"]:  # always keep this order
        if shot_type in shots:
            for exp_id in shots[shot_type]:
                # Construct the pattern that matches your dataframe index
                # Example: "mistral-7B-small_checkworthiness_zero_shot_llm_pred_<id>"
                name = f"{model}_{shot_type.replace('-', '_')}_llm_pred_{exp_id}"
                desired_order.append(name)

# --- Now reorder dataframe safely ---
# Keep only those rows that exist in df (in case some are missing)

df_results = pd.DataFrame(results).transpose()

valid_order = [i for i in desired_order if i in df_results.index]

df_sorted = df_results.loc[valid_order]

df_sorted[["premise0", "premise1", "premise2", "all_premises", "conclusion", "all_args", "all_args_CFS", "all_args_NFS", "all_args_UFS", "all_premises_hate", "all_premises_nohate", "conclusion_hate", "conclusion_nohate"]].to_csv("normal_out.csv")

In [6]:
df_sorted[["premise0", "premise1", "premise2", "all_premises", "conclusion", "all_args", "all_args_CFS", "all_args_NFS", "all_args_UFS", "all_premises_hate", "all_premises_nohate", "conclusion_hate", "conclusion_nohate"]]

,premise0,premise1,premise2,all_premises,conclusion,all_args,all_args_CFS,all_args_NFS,all_args_UFS,all_premises_hate,all_premises_nohate,conclusion_hate,conclusion_nohate
mistral-7B-small_checkworthiness_zero_shot_llm_pred_7cff17b88ad94faa9464b2947940a2d0,0.261062,0.278146,0.275862,0.268473,0.484581,0.345972,0.095890,0.993939,0.196078,0.197970,0.334928,0.449704,0.586207
mistral-7B-small_checkworthiness_zero_shot_llm_pred_95f14e05f4de44b5bc8de54beeb797e8,0.261062,0.278146,0.275862,0.268473,0.484581,0.345972,0.095890,0.993939,0.196078,0.197970,0.334928,0.449704,0.586207
mistral-7B-small_checkworthiness_zero_shot_llm_pred_13e8d5a7a90f4df7955bd560ce954cb9,0.261062,0.271523,0.275862,0.266010,0.484581,0.344392,0.095890,0.993939,0.186275,0.197970,0.330144,0.449704,0.586207
mistral-7B-small_checkworthiness_one_shot_llm_pred_995d1484d0464cb2897b8ea1701ce757,0.389381,0.350993,0.275862,0.366995,0.475771,0.406003,0.210959,0.812121,0.450980,0.269036,0.459330,0.449704,0.551724
mistral-7B-small_checkworthiness_one_shot_llm_pred_c81f652ad938401cac8dc09b2d4af57e,0.380531,0.350993,0.241379,0.359606,0.484581,0.404423,0.213699,0.806061,0.441176,0.258883,0.454545,0.461538,0.551724
mistral-7B-small_checkworthiness_one_shot_llm_pred_40e97314513046ec80d3c564ad524ae1,0.393805,0.350993,0.241379,0.366995,0.484581,0.409163,0.219178,0.812121,0.441176,0.269036,0.459330,0.461538,0.551724
llama-8B-small_checkworthiness_zero_shot_llm_pred_4d0f4bdc75d74ee6a1f69beaa5103388,0.194690,0.218543,0.206897,0.204433,0.449339,0.292259,0.027397,0.987879,0.117647,0.192893,0.215311,0.426036,0.517241
llama-8B-small_checkworthiness_zero_shot_llm_pred_42d9ae35ca4f4d1db16008bdbfc7a9f7,0.194690,0.218543,0.241379,0.206897,0.458150,0.296998,0.032877,0.981818,0.137255,0.192893,0.220096,0.431953,0.534483
llama-8B-small_checkworthiness_zero_shot_llm_pred_daee506eb3694b5788a3ad4dc79be07f,0.194690,0.218543,0.206897,0.204433,0.449339,0.292259,0.027397,0.987879,0.117647,0.192893,0.215311,0.426036,0.517241
llama-8B-small_checkworthiness_one_shot_llm_pred_bed4838077b24457a96f0761d7beccf7,0.225664,0.231788,0.310345,0.233990,0.480176,0.322275,0.079452,0.963636,0.156863,0.213198,0.253589,0.455621,0.551724
llama-8B-small_checkworthiness_one_shot_llm_pred_2c21dfff23874cae87404fd5abd7e313,0.225664,0.238411,0.310345,0.236453,0.480176,0.323855,0.082192,0.963636,0.156863,0.213198,0.258373,0.455621,0.551724
llama-8B-small_checkworthiness_one_shot_llm_pred_cd696bd8a1eb420e9aaecfa5162195c0,0.225664,0.238411,0.310345,0.236453,0.480176,0.323855,0.082192,0.963636,0.156863,0.213198,0.258373,0.455621,0.551724
olmo-7B-small_checkworthiness_zero_shot_llm_pred_3229a4dfda934fda830d0b2effb0298f,0.358407,0.284768,0.275862,0.325123,0.466960,0.375987,0.189041,0.878788,0.235294,0.258883,0.387560,0.437870,0.551724
olmo-7B-small_checkworthiness_zero_shot_llm_pred_50e85531013f40d7abf041c6ff338351,0.371681,0.337748,0.310345,0.354680,0.453744,0.390205,0.213699,0.854545,0.274510,0.274112,0.430622,0.437870,0.500000
olmo-7B-small_checkworthiness_zero_shot_llm_pred_a66c91e48b0840ed9182bd75fdebbb67,0.371681,0.331126,0.310345,0.352217,0.453744,0.388626,0.213699,0.854545,0.264706,0.269036,0.430622,0.437870,0.500000
olmo-7B-small_checkworthiness_one_shot_llm_pred_7fa67fe6a9cc4930a52dcc41e028a13a,0.256637,0.211921,0.275862,0.241379,0.471366,0.323855,0.093151,0.945455,0.147059,0.208122,0.272727,0.431953,0.586207
olmo-7B-small_checkworthiness_one_shot_llm_pred_38630f13f4ca43928f7839f95b0e5ae5,0.252212,0.211921,0.275862,0.238916,0.471366,0.322275,0.090411,0.963636,0.117647,0.208122,0.267943,0.449704,0.534483
olmo-7B-small_checkworthiness_one_shot_llm_pred_72d26a8e05d549269e416358c2477436,0.256637,0.258278,0.310345,0.261084,0.471366,0.336493,0.098630,0.969697,0.166667,0.208122,0.311005,0.449704,0.534483
qwen2.5-7B-small_checkworthiness_zero_shot_llm_pred_2686e66957324dcebb68e7e14209461d,0.296460,0.284768,0.241379,0.288177,0.493392,0.361769,0.101370,0.963636,0.323529,0.243655,0.330144,0.467456,0.568966
qwen2.5-7B-small_checkworthiness_zero_shot_llm_pred_bf33baec21b542a2a17bdced8275fa8b,0.296460,0.304636,0.275862,0.298030,0.488987,0.366509,0.104110,0.963636,0.343137,0.248731,0.344498,0.461538,0.568966
qwen2.5-7B-small_checkworthiness_zero_shot_llm_pred_de923c3de24f4413a20a6eb3b6ba2a76,0.300885,0.284768,0.241379,0.290640,0.497797,0.364929,0.106849,0.963636,0.323529,0.243655,0.334928,0.473373,0.568966
qwen2.5-7B-small_checkworthiness_one_shot_llm_pred_a158fc90640a48fd87adcf2c32af96cd,0.243363,0.225166,0.206897,0.233990,0.449339,0.311216,0.054795,0.993939,0.127451,0.213198,0.253589,0.431953,0.500000
qwen2.5-7B-small_checkworthiness_one_shot_llm_pred_b22d57c18a634050bef8bf13c2df816c,0.247788,0.218543,0.206897,0.233990,0.449339,0.311216,0.054795,0.993939,0.127451,0.213198,0.253589,0.431953,0.500000
qwen2.5-7B-small_checkworthiness_one_shot_llm_pred_409bd7acf1b74e07908c54320ef7e0bf,0.243363,0.231788,0.206897,0.236453,0.453744,0.314376,0.052055,1.000000,0.147059,0.213198,0.258373,0.431953,0.517241
ommandr-7B-small_checkworthiness_zero_shot_llm_pred_2cb5a96289a54a4a84c4934163cf226b,0.424779,0.350993,0.310345,0.389163,0.563877,0.451817,0.410959,0.806061,0.029412,0.406091,0.373206,0.562130,0.568966
ommandr-7B-small_checkworthiness_zero_shot_llm_pred_7e952d9fd707440ca0c36e127482cc56,0.424779,0.390728,0.379310,0.408867,0.568282,0.466035,0.435616,0.793939,0.049020,0.411168,0.406699,0.573964,0.551724
ommandr-7B-small_checkworthiness_zero_shot_llm_pred_50c78f11aa894e7786df46da3b05a890,0.424779,0.344371,0.482759,0.399015,0.559471,0.456556,0.419178,0.781818,0.068627,0.406091,0.392344,0.556213,0.568966
ommandr-7B-small_checkworthiness_one_shot_llm_pred_f300054ab578477e9543926aecdae565,0.371681,0.337748,0.344828,0.357143,0.511013,0.412322,0.323288,0.848485,0.029412,0.360406,0.354067,0.479290,0.603448
ommandr-7B-small_checkworthiness_one_shot_llm_pred_874ee18a6d284a419800f2743b972707,0.371681,0.357616,0.310345,0.362069,0.541850,0.426540,0.345205,0.854545,0.029412,0.375635,0.349282,0.538462,0.551724
ommandr-7B-small_checkworthiness_one_shot_llm_pred_672f5a7d65e645b39070b4a4aeeb2a35,0.376106,0.364238,0.310345,0.366995,0.524229,0.423381,0.342466,0.848485,0.029412,0.385787,0.349282,0.520710,0.534483
mixtral-8x7B-small_checkworthiness_zero_shot_llm_pred_42718aa5c1734282b1d5f86be12abed3,0.623894,0.582781,0.413793,0.593596,0.568282,0.584518,0.698630,0.557576,0.225490,0.598985,0.588517,0.579882,0.534483
mixtral-8x7B-small_checkworthiness_one_shot_llm_pred_e24034b5591e4d3795247f4cbfc6c475,0.566372,0.582781,0.586207,0.573892,0.581498,0.576619,0.660274,0.515152,0.382353,0.568528,0.578947,0.585799,0.568966
mistral-22B-medium_checkworthiness_zero_shot_llm_pred_d8c0afbd8c6b461496d8e323aea7d846,0.265487,0.211921,0.275862,0.246305,0.497797,0.336493,0.123288,0.987879,0.049020,0.223350,0.267943,0.479290,0.551724
mistral-22B-medium_checkworthiness_zero_shot_llm_pred_d3c2a2ee237648b58324fc4cfc87346a,0.265487,0.211921,0.275862,0.246305,0.493392,0.334913,0.120548,0.987879,0.049020,0.223350,0.267943,0.473373,0.551724
mistral-22B-medium_checkworthiness_zero_shot_llm_pred_dd527efae34c42ab82196cc6f0da9595,0.265487,0.211921,0.206897,0.241379,0.488987,0.330174,0.117808,0.981818,0.039216,0.223350,0.258373,0.479290,0.517241
mistral-22B-medium_checkworthiness_one_shot_llm_pred_7251653543d147a490a840ebce03fd21,0.212389,0.205298,0.206897,0.209360,0.471366,0.303318,0.063014,1.000000,0.039216,0.197970,0.220096,0.455621,0.517241
mistral-22B-medium_checkworthiness_one_shot_llm_pred_0c5129b92b6b4fbd97d6b5ed03d5b0e4,0.212389,0.205298,0.206897,0.209360,0.471366,0.303318,0.063014,1.000000,0.039216,0.197970,0.220096,0.455621,0.517241
mistral-22B-medium_checkworthiness_one_shot_llm_pred_7b86bb9eae5747ef94c5521e345d0ba5,0.212389,0.205298,0.206897,0.209360,0.471366,0.303318,0.063014,1.000000,0.039216,0.197970,0.220096,0.455621,0.517241
olmo2-32B-medium_checkworthiness_zero_shot_llm_pred_22493e1f462142fc8b671e105e706036,0.615044,0.549669,0.413793,0.576355,0.629956,0.595577,0.624658,0.739394,0.264706,0.522843,0.626794,0.615385,0.672414
olmo2-32B-medium_checkworthiness_zero_shot_llm_pred_31589a761eff46f29f25be22e615ea84,0.615044,0.549669,0.413793,0.576355,0.612335,0.589258,0.621918,0.727273,0.254902,0.522843,0.626794,0.597633,0.655172
olmo2-32B-medium_checkworthiness_one_shot_llm_pred_9804734bc67745e9bfab6a3abbda4c66,0.500000,0.443709,0.310345,0.465517,0.581498,0.507109,0.435616,0.927273,0.088235,0.426396,0.502392,0.556213,0.655172
olmo2-32B-medium_checkworthiness_one_shot_llm_pred_74aa782b94554dadbac41b88e2a55e13,0.500000,0.443709,0.310345,0.465517,0.577093,0.505529,0.438356,0.921212,0.078431,0.426396,0.502392,0.544379,0.672414
mixtral-8x22B-medium_checkworthiness_zero_shot_llm_pred_ea51bb6edb6c4e79aa215663adb22c13,0.451327,0.370861,0.379310,0.416256,0.550661,0.464455,0.380822,0.915152,0.039216,0.370558,0.459330,0.538462,0.586207
mixtral-8x22B-medium_checkworthiness_one_shot_llm_pred_99f019dae80742e69a971434369103d0,0.513274,0.423841,0.344828,0.467980,0.581498,0.508689,0.432877,0.921212,0.117647,0.431472,0.502392,0.556213,0.655172
llama-70B-big_checkworthiness_zero_shot_llm_pred_ce0707c1e3a0426fbe226774ceac01f7,0.486726,0.377483,0.344828,0.435961,0.550661,0.477093,0.336986,0.987879,0.156863,0.355330,0.511962,0.520710,0.637931
llama-70B-big_checkworthiness_zero_shot_llm_pred_c9dcabb0dbde4746b2dfe72c56d24245,0.482301,0.397351,0.379310,0.443350,0.550661,0.481833,0.339726,0.987879,0.176471,0.355330,0.526316,0.520710,0.637931
llama-70B-big_checkworthiness_one_shot_llm_pred_b90de0ee45b340c69b609a1809206038,0.464602,0.350993,0.344828,0.413793,0.528634,0.454976,0.284932,0.987879,0.205882,0.324873,0.497608,0.508876,0.586207
llama-70B-big_checkworthiness_one_shot_llm_pred_31051c3dfecc49a88080c77b470b4365,0.460177,0.344371,0.344828,0.408867,0.524229,0.450237,0.282192,0.987879,0.186275,0.329949,0.483254,0.502959,0.586207
qwen2.5-72B-big_checkworthiness_zero_shot_llm_pred_e6ca32e4ac724205aeca7c9f7d5ac015,0.482301,0.437086,0.448276,0.463054,0.519824,0.483412,0.290411,0.969697,0.392157,0.355330,0.564593,0.491124,0.603448
qwen2.5-72B-big_checkworthiness_zero_shot_llm_pred_851646123c0a4150938988be249ba5a3,0.482301,0.423841,0.413793,0.455665,0.537445,0.484992,0.293151,0.975758,0.382353,0.360406,0.545455,0.508876,0.620690
qwen2.5-72B-big_checkworthiness_one_shot_llm_pred_1f457c7d1aca447fb8c292e0ce7861fc,0.455752,0.357616,0.310345,0.408867,0.519824,0.448657,0.246575,0.987879,0.303922,0.309645,0.502392,0.491124,0.603448
qwen2.5-72B-big_checkworthiness_one_shot_llm_pred_014277e19af4488f97128047d4d7b936,0.455752,0.370861,0.344828,0.416256,0.524229,0.454976,0.243836,0.987879,0.352941,0.309645,0.516746,0.485207,0.637931
ommandr-104B-big_checkworthiness_zero_shot_llm_pred_99977df7b2044889b1c188ea7941ae5f,0.517699,0.476821,0.413793,0.495074,0.629956,0.543444,0.547945,0.872727,0.000000,0.543147,0.449761,0.627219,0.637931
ommandr-104B-big_checkworthiness_zero_shot_llm_pred_4b38fb694add4ec59378324ecadd4b49,0.513274,0.476821,0.379310,0.490148,0.621145,0.537125,0.528767,0.884848,0.009804,0.543147,0.440191,0.627219,0.603448
ommandr-104B-big_checkworthiness_one_shot_llm_pred_d1f57836592341d7bf1142aa7b767fca,0.256637,0.211921,0.310345,0.243842,0.480176,0.328594,0.112329,1.000000,0.019608,0.228426,0.258373,0.467456,0.517241
ommandr-104B-big_checkworthiness_one_shot_llm_pred_e89477f022c24d4e855ba2ce01b63f9e,0.256637,0.192053,0.275862,0.233990,0.480176,0.322275,0.104110,1.000000,0.009804,0.228426,0.239234,0.467456,0.517241

In [ ]:
df_results

In [37]:
df_results

,premise0,premise1,premise2,conclusion,conclusion_hate,conclusion_nohate,all_premises,all_args,all_args_CFS,all_args_NFS,all_args_UFS,all_premises_hate,all_premises_nohate
mixtral-8x7B-small_checkworthiness_zero_shot_llm_pred_42718aa5c1734282b1d5f86be12abed3,0.623894,0.576159,0.344828,0.563877,0.579882,0.517241,0.586207,0.578199,0.696970,0.558282,0.217822,0.593909,0.578947
olmo2-32B-medium_checkworthiness_zero_shot_llm_pred_22493e1f462142fc8b671e105e706036,0.615044,0.543046,0.310345,0.625551,0.615385,0.655172,0.566502,0.587678,0.622590,0.736196,0.257426,0.517766,0.612440
olmo-7B-small_checkworthiness_zero_shot_llm_pred_3229a4dfda934fda830d0b2effb0298f,0.358407,0.284768,0.172414,0.466960,0.437870,0.551724,0.317734,0.371248,0.187328,0.877301,0.237624,0.253807,0.377990
mistral-22B-medium_checkworthiness_zero_shot_llm_pred_a8a9c0451b49433ea5cd920fb68e3649,0.261062,0.211921,0.137931,0.493392,0.479290,0.534483,0.233990,0.327014,0.115702,0.987730,0.039604,0.213198,0.253589
mistral-22B-medium_checkworthiness_zero_shot_llm_pred_d8c0afbd8c6b461496d8e323aea7d846,0.265487,0.211921,0.172414,0.493392,0.479290,0.534483,0.238916,0.330174,0.121212,0.987730,0.039604,0.218274,0.258373
olmo-7B-small_checkworthiness_zero_shot_llm_pred_50e85531013f40d7abf041c6ff338351,0.371681,0.337748,0.206897,0.449339,0.437870,0.482759,0.347291,0.383886,0.212121,0.852761,0.267327,0.269036,0.421053
mistral-7B-small_checkworthiness_zero_shot_llm_pred_7cff17b88ad94faa9464b2947940a2d0,0.261062,0.278146,0.172414,0.480176,0.449704,0.568966,0.261084,0.339652,0.093664,0.993865,0.188119,0.192893,0.325359
llama-8B-small_checkworthiness_zero_shot_llm_pred_4d0f4bdc75d74ee6a1f69beaa5103388,0.194690,0.218543,0.137931,0.449339,0.426036,0.517241,0.199507,0.289100,0.027548,0.987730,0.118812,0.187817,0.210526
ommandr-7B-small_checkworthiness_zero_shot_llm_pred_2cb5a96289a54a4a84c4934163cf226b,0.424779,0.344371,0.241379,0.563877,0.562130,0.568966,0.381773,0.447077,0.407713,0.809816,0.029703,0.406091,0.358852
llama-70B-big_checkworthiness_zero_shot_llm_pred_ce0707c1e3a0426fbe226774ceac01f7,0.486726,0.377483,0.241379,0.546256,0.520710,0.620690,0.428571,0.470774,0.336088,0.987730,0.148515,0.350254,0.502392
olmo-7B-small_checkworthiness_zero_shot_llm_pred_a66c91e48b0840ed9182bd75fdebbb67,0.371681,0.331126,0.206897,0.449339,0.437870,0.482759,0.344828,0.382306,0.212121,0.852761,0.257426,0.263959,0.421053
mixtral-8x22B-medium_checkworthiness_zero_shot_llm_pred_ea51bb6edb6c4e79aa215663adb22c13,0.451327,0.370861,0.275862,0.550661,0.538462,0.586207,0.408867,0.459716,0.380165,0.914110,0.039604,0.365482,0.449761
ommandr-7B-small_checkworthiness_zero_shot_llm_pred_7e952d9fd707440ca0c36e127482cc56,0.424779,0.384106,0.275862,0.568282,0.573964,0.551724,0.399015,0.459716,0.432507,0.791411,0.049505,0.406091,0.392344
mistral-22B-medium_checkworthiness_zero_shot_llm_pred_d3c2a2ee237648b58324fc4cfc87346a,0.265487,0.211921,0.172414,0.488987,0.473373,0.534483,0.238916,0.328594,0.118457,0.987730,0.039604,0.218274,0.258373
mixtral-8x22B-big_checkworthiness_zero_shot_llm_pred_255fd733ab3641e19f95c1823ef5923c,0.455752,0.364238,0.241379,0.555066,0.544379,0.586207,0.406404,0.459716,0.371901,0.926380,0.049505,0.365482,0.444976
mistral-7B-small_checkworthiness_zero_shot_llm_pred_95f14e05f4de44b5bc8de54beeb797e8,0.261062,0.278146,0.172414,0.480176,0.449704,0.568966,0.261084,0.339652,0.093664,0.993865,0.188119,0.192893,0.325359
olmo2-32B-medium_checkworthiness_zero_shot_llm_pred_31589a761eff46f29f25be22e615ea84,0.615044,0.543046,0.310345,0.607930,0.597633,0.637931,0.566502,0.581359,0.619835,0.723926,0.247525,0.517766,0.612440
llama-8B-small_checkworthiness_zero_shot_llm_pred_42d9ae35ca4f4d1db16008bdbfc7a9f7,0.194690,0.218543,0.172414,0.453744,0.431953,0.517241,0.201970,0.292259,0.033058,0.981595,0.128713,0.187817,0.215311
mistral-7B-small_checkworthiness_zero_shot_llm_pred_13e8d5a7a90f4df7955bd560ce954cb9,0.261062,0.271523,0.172414,0.480176,0.449704,0.568966,0.258621,0.338073,0.093664,0.993865,0.178218,0.192893,0.320574
llama-8B-small_checkworthiness_zero_shot_llm_pred_daee506eb3694b5788a3ad4dc79be07f,0.194690,0.218543,0.137931,0.449339,0.426036,0.517241,0.199507,0.289100,0.027548,0.987730,0.118812,0.187817,0.210526
qwen2.5-7B-small_checkworthiness_zero_shot_llm_pred_2686e66957324dcebb68e7e14209461d,0.296460,0.284768,0.172414,0.488987,0.467456,0.551724,0.283251,0.357030,0.101928,0.963190,0.316832,0.238579,0.325359
qwen2.5-7B-small_checkworthiness_zero_shot_llm_pred_bf33baec21b542a2a17bdced8275fa8b,0.296460,0.304636,0.206897,0.484581,0.461538,0.551724,0.293103,0.361769,0.104683,0.963190,0.336634,0.243655,0.339713
llama-70B-big_checkworthiness_zero_shot_llm_pred_c9dcabb0dbde4746b2dfe72c56d24245,0.482301,0.397351,0.275862,0.546256,0.520710,0.620690,0.435961,0.475513,0.338843,0.987730,0.168317,0.350254,0.516746
mistral-22B-medium_checkworthiness_zero_shot_llm_pred_dd527efae34c42ab82196cc6f0da9595,0.265487,0.211921,0.137931,0.488987,0.479290,0.517241,0.236453,0.327014,0.118457,0.981595,0.039604,0.218274,0.253589
ommandr-104B-big_checkworthiness_zero_shot_llm_pred_99977df7b2044889b1c188ea7941ae5f,0.517699,0.470199,0.310345,0.629956,0.627219,0.637931,0.485222,0.537125,0.545455,0.871166,0.000000,0.538071,0.435407
qwen2.5-72B-big_checkworthiness_zero_shot_llm_pred_e6ca32e4ac724205aeca7c9f7d5ac015,0.482301,0.437086,0.344828,0.515419,0.491124,0.586207,0.455665,0.477093,0.289256,0.969325,0.386139,0.350254,0.555024
ommandr-104B-big_checkworthiness_zero_shot_llm_pred_4b38fb694add4ec59378324ecadd4b49,0.513274,0.470199,0.275862,0.621145,0.627219,0.603448,0.480296,0.530806,0.526171,0.883436,0.009901,0.538071,0.425837
qwen2.5-72B-big_checkworthiness_zero_shot_llm_pred_851646123c0a4150938988be249ba5a3,0.482301,0.423841,0.310345,0.533040,0.508876,0.603448,0.448276,0.478673,0.292011,0.975460,0.376238,0.355330,0.535885
ommandr-7B-small_checkworthiness_zero_shot_llm_pred_50c78f11aa894e7786df46da3b05a890,0.424779,0.337748,0.379310,0.559471,0.556213,0.568966,0.389163,0.450237,0.415978,0.779141,0.069307,0.401015,0.377990
qwen2.5-7B-small_checkworthiness_zero_shot_llm_pred_de923c3de24f4413a20a6eb3b6ba2a76,0.300885,0.284768,0.172414,0.493392,0.473373,0.551724,0.285714,0.360190,0.107438,0.963190,0.316832,0.238579,0.330144
mistral-7B-small_checkworthiness_one_shot_llm_pred_995d1484d0464cb2897b8ea1701ce757,0.389381,0.350993,0.206897,0.471366,0.449704,0.534483,0.362069,0.401264,0.209366,0.815951,0.445545,0.263959,0.454545
qwen2.5-7B-small_checkworthiness_one_shot_llm_pred_a158fc90640a48fd87adcf2c32af96cd,0.243363,0.225166,0.137931,0.449339,0.431953,0.500000,0.229064,0.308057,0.055096,0.993865,0.128713,0.208122,0.248804
mixtral-8x7B-small_checkworthiness_one_shot_llm_pred_e24034b5591e4d3795247f4cbfc6c475,0.566372,0.576159,0.482759,0.577093,0.585799,0.551724,0.564039,0.568720,0.658402,0.509202,0.376238,0.563452,0.564593
ommandr-7B-small_checkworthiness_one_shot_llm_pred_f300054ab578477e9543926aecdae565,0.371681,0.337748,0.241379,0.511013,0.479290,0.603448,0.349754,0.407583,0.322314,0.846626,0.029703,0.355330,0.344498
qwen2.5-72B-big_checkworthiness_one_shot_llm_pred_1f457c7d1aca447fb8c292e0ce7861fc,0.455752,0.357616,0.206897,0.515419,0.491124,0.586207,0.401478,0.442338,0.245179,0.987730,0.297030,0.304569,0.492823
llama-8B-small_checkworthiness_one_shot_llm_pred_bed4838077b24457a96f0761d7beccf7,0.225664,0.231788,0.206897,0.480176,0.455621,0.551724,0.226601,0.317536,0.077135,0.963190,0.158416,0.208122,0.244019
ommandr-104B-big_checkworthiness_one_shot_llm_pred_d1f57836592341d7bf1142aa7b767fca,0.256637,0.211921,0.206897,0.480176,0.467456,0.517241,0.236453,0.323855,0.110193,1.000000,0.019802,0.223350,0.248804
olmo-7B-small_checkworthiness_one_shot_llm_pred_7fa67fe6a9cc4930a52dcc41e028a13a,0.256637,0.211921,0.206897,0.466960,0.431953,0.568966,0.236453,0.319115,0.093664,0.944785,0.138614,0.203046,0.267943
mixtral-8x22B-big_checkworthiness_one_shot_llm_pred_6b9fc2f3b96943c4925fef062a7ac144,0.522124,0.410596,0.172414,0.585903,0.568047,0.637931,0.455665,0.502370,0.432507,0.926380,0.099010,0.406091,0.502392
olmo-7B-small_checkworthiness_one_shot_llm_pred_38630f13f4ca43928f7839f95b0e5ae5,0.252212,0.211921,0.206897,0.471366,0.449704,0.534483,0.233990,0.319115,0.090909,0.963190,0.118812,0.203046,0.263158
llama-8B-small_checkworthiness_one_shot_llm_pred_2c21dfff23874cae87404fd5abd7e313,0.225664,0.238411,0.206897,0.480176,0.455621,0.551724,0.229064,0.319115,0.079890,0.963190,0.158416,0.208122,0.248804
mistral-7B-small_checkworthiness_one_shot_llm_pred_c81f652ad938401cac8dc09b2d4af57e,0.380531,0.350993,0.172414,0.480176,0.461538,0.534483,0.354680,0.399684,0.212121,0.809816,0.435644,0.253807,0.449761
llama-8B-small_checkworthiness_one_shot_llm_pred_cd696bd8a1eb420e9aaecfa5162195c0,0.225664,0.238411,0.206897,0.480176,0.455621,0.551724,0.229064,0.319115,0.079890,0.963190,0.158416,0.208122,0.248804
ommandr-104B-big_checkworthiness_one_shot_llm_pred_e89477f022c24d4e855ba2ce01b63f9e,0.256637,0.192053,0.172414,0.480176,0.467456,0.517241,0.226601,0.317536,0.101928,1.000000,0.009901,0.223350,0.229665
qwen2.5-7B-small_checkworthiness_one_shot_llm_pred_b22d57c18a634050bef8bf13c2df816c,0.247788,0.218543,0.137931,0.449339,0.431953,0.500000,0.229064,0.308057,0.055096,0.993865,0.128713,0.208122,0.248804
mistral-22B-medium_checkworthiness_one_shot_llm_pred_d4fa9437728e46dfb495dca826ead768,0.212389,0.205298,0.137931,0.471366,0.455621,0.517241,0.204433,0.300158,0.063361,1.000000,0.039604,0.192893,0.215311
mistral-22B-medium_checkworthiness_one_shot_llm_pred_7251653543d147a490a840ebce03fd21,0.212389,0.205298,0.137931,0.471366,0.455621,0.517241,0.204433,0.300158,0.063361,1.000000,0.039604,0.192893,0.215311
mixtral-8x22B-medium_checkworthiness_one_shot_llm_pred_99f019dae80742e69a971434369103d0,0.513274,0.423841,0.241379,0.577093,0.556213,0.637931,0.460591,0.502370,0.432507,0.920245,0.108911,0.426396,0.492823
llama-70B-big_checkworthiness_one_shot_llm_pred_b90de0ee45b340c69b609a1809206038,0.464602,0.350993,0.241379,0.528634,0.508876,0.586207,0.406404,0.450237,0.283747,0.987730,0.207921,0.319797,0.488038
llama-70B-big_checkworthiness_one_shot_llm_pred_31051c3dfecc49a88080c77b470b4365,0.460177,0.344371,0.241379,0.524229,0.502959,0.586207,0.401478,0.445498,0.280992,0.987730,0.188119,0.324873,0.473684
ommandr-7B-small_checkworthiness_one_shot_llm_pred_874ee18a6d284a419800f2743b972707,0.371681,0.350993,0.241379,0.541850,0.538462,0.551724,0.354680,0.421801,0.344353,0.852761,0.029703,0.370558,0.339713
mistral-22B-medium_checkworthiness_one_shot_llm_pred_0c5129b92b6b4fbd97d6b5ed03d5b0e4,0.212389,0.205298,0.137931,0.471366,0.455621,0.517241,0.204433,0.300158,0.063361,1.000000,0.039604,0.192893,0.215311
qwen2.5-72B-big_checkworthiness_one_shot_llm_pred_014277e19af4488f97128047d4d7b936,0.455752,0.370861,0.241379,0.519824,0.485207,0.620690,0.408867,0.448657,0.242424,0.987730,0.346535,0.304569,0.507177
ommandr-7B-small_checkworthiness_one_shot_llm_pred_672f5a7d65e645b39070b4a4aeeb2a35,0.376106,0.357616,0.241379,0.524229,0.520710,0.534483,0.359606,0.418641,0.341598,0.846626,0.029703,0.380711,0.339713
olmo2-32B-medium_checkworthiness_one_shot_llm_pred_9804734bc67745e9bfab6a3abbda4c66,0.500000,0.437086,0.206897,0.577093,0.556213,0.637931,0.455665,0.499210,0.432507,0.926380,0.079208,0.421320,0.488038
qwen2.5-7B-small_checkworthiness_one_shot_llm_pred_409bd7acf1b74e07908c54320ef7e0bf,0.243363,0.231788,0.137931,0.453744,0.431953,0.517241,0.231527,0.311216,0.052342,1.000000,0.148515,0.208122,0.253589
olmo2-32B-medium_checkworthiness_one_shot_llm_pred_74aa782b94554dadbac41b88e2a55e13,0.500000,0.437086,0.206897,0.572687,0.544379,0.655172,0.455665,0.497630,0.435262,0.920245,0.069307,0.421320,0.488038
mistral-22B-medium_checkworthiness_one_shot_llm_pred_7b86bb9eae5747ef94c5521e345d0ba5,0.212389,0.205298,0.137931,0.471366,0.455621,0.517241,0.204433,0.300158,0.063361,1.000000,0.039604,0.192893,0.215311
mistral-7B-small_checkworthiness_one_shot_llm_pred_40e97314513046ec80d3c564ad524ae1,0.393805,0.350993,0.172414,0.480176,0.461538,0.534483,0.362069,0.404423,0.217631,0.815951,0.435644,0.263959,0.454545
olmo-7B-small_checkworthiness_one_shot_llm_pred_72d26a8e05d549269e416358c2477436,0.256637,0.258278,0.206897,0.471366,0.449704,0.534483,0.253695,0.331754,0.096419,0.969325,0.168317,0.203046,0.301435

In [30]:
df_sorted[["premise0", "premise1", "premise2", "all_premises", "conclusion", "all_args", "all_args_CFS", "all_args_NFS", "all_args_UFS", "all_premises_hate", "all_premises_nohate", "conclusion_hate", "conclusion_nohate"]]

Empty DataFrame
Columns: [premise0, premise1, premise2, all_premises, conclusion, all_args, all_args_CFS, all_args_NFS, all_args_UFS, all_premises_hate, all_premises_nohate, conclusion_hate, conclusion_nohate]
Index: []

In [184]:

# Example: df is your dataframe with those indices
# df = pd.DataFrame(...)

# Custom order for models
model_order = [
    "mistral-7B",
    "llama-8B",
    "olmo-7B",      # (you wrote olmo2-7b, but in your list it's `olmo-7B`)
    "qwen2.5-7B",
    "ommandr-7B",
    "mixtral-8x7B",
    "mistral-22B",
    "olmo2-32B",
    "mixtral-8x22B",
    "llama-70B",
    "qwen2.5-72B",
    "ommandr-104B"
]

# Custom order for shot type
shot_order = ["zero_shot", "one_shot"]

# Build a ranking dict for sorting
order_dict = {
    f"{model}_{shot}": i
    for model_idx, model in enumerate(model_order)
    for shot_idx, shot in enumerate(shot_order)
    for i in [model_idx * len(shot_order) + shot_idx]
}

# Function to extract the relevant key
def extract_key(idx):
    for model in model_order:
        if idx.startswith(model):
            shot = "zero_shot" if "zero_shot" in idx else "one_shot"
            return f"{model}_{shot}"
    return None

# Sort index based on our ranking
df_res = pd.DataFrame(results).transpose()
df_res_sorted = df_res.loc[sorted(df_res.index, key=lambda x: order_dict.get(extract_key(x), 1e9))]

,premise0,premise1,premise2,all_premises,conclusion,all_args,all_args_CFS,all_args_NFS,all_args_UFS,all_premises_hate,all_premises_nohate,conclusion_hate,conclusion_nohate
mistral-7B-small_checkworthiness_zero_shot_llm_pred__7cff17b88ad94faa9464b2947940a2d0,0.261062,0.278146,0.172414,0.261084,0.480176,0.339652,0.093664,0.993865,0.188119,0.192893,0.325359,0.449704,0.568966
mistral-7B-small_checkworthiness_zero_shot_llm_pred__13e8d5a7a90f4df7955bd560ce954cb9,0.261062,0.271523,0.172414,0.258621,0.480176,0.338073,0.093664,0.993865,0.178218,0.192893,0.320574,0.449704,0.568966
mistral-7B-small_checkworthiness_one_shot_llm_pred__995d1484d0464cb2897b8ea1701ce757,0.389381,0.350993,0.206897,0.362069,0.471366,0.401264,0.209366,0.815951,0.445545,0.263959,0.454545,0.449704,0.534483
mistral-7B-small_checkworthiness_one_shot_llm_pred__40e97314513046ec80d3c564ad524ae1,0.393805,0.350993,0.172414,0.362069,0.480176,0.404423,0.217631,0.815951,0.435644,0.263959,0.454545,0.461538,0.534483
llama-8B-small_checkworthiness_zero_shot_llm_pred__42d9ae35ca4f4d1db16008bdbfc7a9f7,0.194690,0.218543,0.172414,0.201970,0.453744,0.292259,0.033058,0.981595,0.128713,0.187817,0.215311,0.431953,0.517241
llama-8B-small_checkworthiness_zero_shot_llm_pred__daee506eb3694b5788a3ad4dc79be07f,0.194690,0.218543,0.137931,0.199507,0.449339,0.289100,0.027548,0.987730,0.118812,0.187817,0.210526,0.426036,0.517241
llama-8B-small_checkworthiness_one_shot_llm_pred__bed4838077b24457a96f0761d7beccf7,0.225664,0.231788,0.206897,0.226601,0.480176,0.317536,0.077135,0.963190,0.158416,0.208122,0.244019,0.455621,0.551724
llama-8B-small_checkworthiness_one_shot_llm_pred__2c21dfff23874cae87404fd5abd7e313,0.225664,0.238411,0.206897,0.229064,0.480176,0.319115,0.079890,0.963190,0.158416,0.208122,0.248804,0.455621,0.551724
olmo-7B-small_checkworthiness_zero_shot_llm_pred__3229a4dfda934fda830d0b2effb0298f,0.358407,0.284768,0.172414,0.317734,0.466960,0.371248,0.187328,0.877301,0.237624,0.253807,0.377990,0.437870,0.551724
olmo-7B-small_checkworthiness_zero_shot_llm_pred__a66c91e48b0840ed9182bd75fdebbb67,0.371681,0.331126,0.206897,0.344828,0.449339,0.382306,0.212121,0.852761,0.257426,0.263959,0.421053,0.437870,0.482759
olmo-7B-small_checkworthiness_one_shot_llm_pred__38630f13f4ca43928f7839f95b0e5ae5,0.252212,0.211921,0.206897,0.233990,0.471366,0.319115,0.090909,0.963190,0.118812,0.203046,0.263158,0.449704,0.534483
olmo-7B-small_checkworthiness_one_shot_llm_pred__72d26a8e05d549269e416358c2477436,0.256637,0.258278,0.206897,0.253695,0.471366,0.331754,0.096419,0.969325,0.168317,0.203046,0.301435,0.449704,0.534483
qwen2.5-7B-small_checkworthiness_zero_shot_llm_pred__bf33baec21b542a2a17bdced8275fa8b,0.296460,0.304636,0.206897,0.293103,0.484581,0.361769,0.104683,0.963190,0.336634,0.243655,0.339713,0.461538,0.551724
qwen2.5-7B-small_checkworthiness_zero_shot_llm_pred__de923c3de24f4413a20a6eb3b6ba2a76,0.300885,0.284768,0.172414,0.285714,0.493392,0.360190,0.107438,0.963190,0.316832,0.238579,0.330144,0.473373,0.551724
qwen2.5-7B-small_checkworthiness_one_shot_llm_pred__a158fc90640a48fd87adcf2c32af96cd,0.243363,0.225166,0.137931,0.229064,0.449339,0.308057,0.055096,0.993865,0.128713,0.208122,0.248804,0.431953,0.500000
qwen2.5-7B-small_checkworthiness_one_shot_llm_pred__b22d57c18a634050bef8bf13c2df816c,0.247788,0.218543,0.137931,0.229064,0.449339,0.308057,0.055096,0.993865,0.128713,0.208122,0.248804,0.431953,0.500000
ommandr-7B-small_checkworthiness_zero_shot_llm_pred__7e952d9fd707440ca0c36e127482cc56,0.424779,0.384106,0.275862,0.399015,0.568282,0.459716,0.432507,0.791411,0.049505,0.406091,0.392344,0.573964,0.551724
ommandr-7B-small_checkworthiness_zero_shot_llm_pred__50c78f11aa894e7786df46da3b05a890,0.424779,0.337748,0.379310,0.389163,0.559471,0.450237,0.415978,0.779141,0.069307,0.401015,0.377990,0.556213,0.568966
ommandr-7B-small_checkworthiness_one_shot_llm_pred__f300054ab578477e9543926aecdae565,0.371681,0.337748,0.241379,0.349754,0.511013,0.407583,0.322314,0.846626,0.029703,0.355330,0.344498,0.479290,0.603448
ommandr-7B-small_checkworthiness_one_shot_llm_pred__672f5a7d65e645b39070b4a4aeeb2a35,0.376106,0.357616,0.241379,0.359606,0.524229,0.418641,0.341598,0.846626,0.029703,0.380711,0.339713,0.520710,0.534483
mixtral-8x7B-small_checkworthiness_zero_shot_llm_pred__42718aa5c1734282b1d5f86be12abed3,0.623894,0.576159,0.344828,0.586207,0.563877,0.578199,0.696970,0.558282,0.217822,0.593909,0.578947,0.579882,0.517241
mixtral-8x7B-small_checkworthiness_one_shot_llm_pred__e24034b5591e4d3795247f4cbfc6c475,0.566372,0.576159,0.482759,0.564039,0.577093,0.568720,0.658402,0.509202,0.376238,0.563452,0.564593,0.585799,0.551724
mistral-22B-medium_checkworthiness_zero_shot_llm_pred__d8c0afbd8c6b461496d8e323aea7d846,0.265487,0.211921,0.172414,0.238916,0.493392,0.330174,0.121212,0.987730,0.039604,0.218274,0.258373,0.479290,0.534483
mistral-22B-medium_checkworthiness_zero_shot_llm_pred__d3c2a2ee237648b58324fc4cfc87346a,0.265487,0.211921,0.172414,0.238916,0.488987,0.328594,0.118457,0.987730,0.039604,0.218274,0.258373,0.473373,0.534483
mistral-22B-medium_checkworthiness_zero_shot_llm_pred__dd527efae34c42ab82196cc6f0da9595,0.265487,0.211921,0.137931,0.236453,0.488987,0.327014,0.118457,0.981595,0.039604,0.218274,0.253589,0.479290,0.517241
mistral-22B-medium_checkworthiness_one_shot_llm_pred__d4fa9437728e46dfb495dca826ead768,0.212389,0.205298,0.137931,0.204433,0.471366,0.300158,0.063361,1.000000,0.039604,0.192893,0.215311,0.455621,0.517241
mistral-22B-medium_checkworthiness_one_shot_llm_pred__7251653543d147a490a840ebce03fd21,0.212389,0.205298,0.137931,0.204433,0.471366,0.300158,0.063361,1.000000,0.039604,0.192893,0.215311,0.455621,0.517241
mistral-22B-medium_checkworthiness_one_shot_llm_pred__7b86bb9eae5747ef94c5521e345d0ba5,0.212389,0.205298,0.137931,0.204433,0.471366,0.300158,0.063361,1.000000,0.039604,0.192893,0.215311,0.455621,0.517241
olmo2-32B-medium_checkworthiness_zero_shot_llm_pred__22493e1f462142fc8b671e105e706036,0.615044,0.543046,0.310345,0.566502,0.625551,0.587678,0.622590,0.736196,0.257426,0.517766,0.612440,0.615385,0.655172
olmo2-32B-medium_checkworthiness_one_shot_llm_pred__74aa782b94554dadbac41b88e2a55e13,0.500000,0.437086,0.206897,0.455665,0.572687,0.497630,0.435262,0.920245,0.069307,0.421320,0.488038,0.544379,0.655172
mixtral-8x22B-big_checkworthiness_zero_shot_llm_pred__255fd733ab3641e19f95c1823ef5923c,0.455752,0.364238,0.241379,0.406404,0.555066,0.459716,0.371901,0.926380,0.049505,0.365482,0.444976,0.544379,0.586207
mixtral-8x22B-big_checkworthiness_one_shot_llm_pred__6b9fc2f3b96943c4925fef062a7ac144,0.522124,0.410596,0.172414,0.455665,0.585903,0.502370,0.432507,0.926380,0.099010,0.406091,0.502392,0.568047,0.637931
llama-70B-big_checkworthiness_zero_shot_llm_pred__c9dcabb0dbde4746b2dfe72c56d24245,0.482301,0.397351,0.275862,0.435961,0.546256,0.475513,0.338843,0.987730,0.168317,0.350254,0.516746,0.520710,0.620690
llama-70B-big_checkworthiness_one_shot_llm_pred__31051c3dfecc49a88080c77b470b4365,0.460177,0.344371,0.241379,0.401478,0.524229,0.445498,0.280992,0.987730,0.188119,0.324873,0.473684,0.502959,0.586207
qwen2.5-72B-big_checkworthiness_zero_shot_llm_pred__e6ca32e4ac724205aeca7c9f7d5ac015,0.482301,0.437086,0.344828,0.455665,0.515419,0.477093,0.289256,0.969325,0.386139,0.350254,0.555024,0.491124,0.586207
qwen2.5-72B-big_checkworthiness_one_shot_llm_pred__1f457c7d1aca447fb8c292e0ce7861fc,0.455752,0.357616,0.206897,0.401478,0.515419,0.442338,0.245179,0.987730,0.297030,0.304569,0.492823,0.491124,0.586207
ommandr-104B-big_checkworthiness_zero_shot_llm_pred__4b38fb694add4ec59378324ecadd4b49,0.513274,0.470199,0.275862,0.480296,0.621145,0.530806,0.526171,0.883436,0.009901,0.538071,0.425837,0.627219,0.603448
ommandr-104B-big_checkworthiness_one_shot_llm_pred__e89477f022c24d4e855ba2ce01b63f9e,0.256637,0.192053,0.172414,0.226601,0.480176,0.317536,0.101928,1.000000,0.009901,0.223350,0.229665,0.467456,0.517241

In [185]:
df_res_sorted[["premise0", "premise1", "premise2", "all_premises", "conclusion", "all_args", "all_args_CFS", "all_args_NFS", "all_args_UFS", "all_premises_hate", "all_premises_nohate", "conclusion_hate", "conclusion_nohate"]].to_csv("normal_out.csv")

In [24]:
import pandas as pd

cols = ["premise0", "premise1", "premise2", "conclusion"]

results = {}
for path in htaxon:
    experiment_name = path.split("/")[-1].strip(".csv")
    results[experiment_name] = {}

    df = pd.read_csv(path)

    df = df.rename(
        columns={
            "premise0_llm_pred": "y_pred_premise0_cw",
            "premise1_llm_pred": "y_pred_premise1_cw",
            "premise2_llm_pred": "y_pred_premise2_cw",
            "conclusion_llm_pred": "y_pred_conclusion_cw",
            "hate_taxon_premise0": "y_label_premise0_cw",
            "hate_taxon_premise1": "y_label_premise1_cw",
            "hate_taxon_premise2": "y_label_premise2_cw",
            "hate_taxon_conclusion": "y_label_conclusion_cw",
        }
    )

    correct_per_arg = {"args_pred": [], "args_label": []}
    for c in cols:
        y_pred = df.loc[~df[c].isna(), f"y_pred_{c}_cw"]
        y_label = df.loc[~df[c].isna(), f"y_label_{c}_cw"]
        correct_per_arg["args_pred"].extend(y_pred.tolist())
        correct_per_arg["args_label"].extend(y_label.tolist())

        results[experiment_name][c] = (y_label == y_pred).sum() / len(y_label)

    correct_per_arg_df = pd.DataFrame(correct_per_arg)
    results[experiment_name]["all_args"] = (
        (correct_per_arg_df["args_pred"] == correct_per_arg_df["args_label"]).sum()
    ) / len(correct_per_arg_df)

    nof_wg = len(correct_per_arg_df[correct_per_arg_df["args_label"] == "White Grievance"])
    acc_wg = (
        (correct_per_arg_df["args_pred"] == correct_per_arg_df["args_label"])
        & (correct_per_arg_df["args_label"] == "White Grievance")
    ).sum() / nof_wg
    results[experiment_name]["all_args_white_grievance"] = acc_wg

    nof_iv = len(correct_per_arg_df[correct_per_arg_df["args_label"] == "Incitement to Violence"])
    acc_iv = (
        (correct_per_arg_df["args_pred"] == correct_per_arg_df["args_label"])
        & (correct_per_arg_df["args_label"] == "Incitement to Violence")
    ).sum() / nof_iv
    results[experiment_name]["all_args_incitement_violence"] = acc_iv

    nof_il = len(correct_per_arg_df[correct_per_arg_df["args_label"] == "Inferiority Language"])
    acc_il = (
        (correct_per_arg_df["args_pred"] == correct_per_arg_df["args_label"])
        & (correct_per_arg_df["args_label"] == "Inferiority Language")
    ).sum() / nof_il
    results[experiment_name]["all_args_inferiority_language"] = acc_il

    nof_iro = len(correct_per_arg_df[correct_per_arg_df["args_label"] == "Irony"])
    acc_iro = (
        (correct_per_arg_df["args_pred"] == correct_per_arg_df["args_label"])
        & (correct_per_arg_df["args_label"] == "Irony")
    ).sum() / nof_iro
    results[experiment_name]["all_args_inferiority_language"] = acc_iro

    nof_stereotype = len(correct_per_arg_df[correct_per_arg_df["args_label"] == "Stereotypes and Misinformation"])
    acc_stereotype = (
        (correct_per_arg_df["args_pred"] == correct_per_arg_df["args_label"])
        & (correct_per_arg_df["args_label"] == "Stereotypes and Misinformation")
    ).sum() / nof_stereotype
    results[experiment_name]["all_args_inferiority_language"] = acc_stereotype

    nof_threat = len(correct_per_arg_df[correct_per_arg_df["args_label"] == "Threatening and Intimidation"])
    acc_threat = (
        (correct_per_arg_df["args_pred"] == correct_per_arg_df["args_label"])
        & (correct_per_arg_df["args_label"] == "Threatening and Intimidation")
    ).sum() / nof_threat
    results[experiment_name]["all_args_inferiority_language"] = acc_threat

KeyError: 'y_label_premise0_cw'

["White Grievance", "Incitement to Violence", "Inferiority Language", "Irony", "Stereotypes and Misinformation", "Threatening and Intimidation"]

In [25]:
df

,file_id,idx,text_ed,IS,premise0,check_worthy_premise0,truth-o-meter_premise0,comments_premise0,premise1,check_worthy_premise1,...,premise0_hate,premise1_hate,premise2_hate,conclusion_hate,arg_comps_ok,target_ok,y_pred_premise0_cw,y_pred_premise1_cw,y_pred_premise2_cw,y_pred_conclusion_cw
0,30679934_1,0,the kind of perversion that leads to homosexua...,gay men are perverts.,The kind of perversion that leads to homosexua...,CFS,pants-fire,association fallacy?,Gay men may turn out to be pedophiles.,CFS,...,1.0,1.0,0.0,1.0,1.0,1.0,Threatening and Intimidation,Threatening and Intimidation,Irony,Threatening and Intimidation
1,13470210_2,1,The Jews say they are The Chosen Ones The Blac...,jewish people are inferior to other groups.,The Jews believe they are The Chosen Ones.,CFS,false?,stereotype? generalizes and potentially misrep...,The Blacks claim to be the original Hebrews an...,CFS,...,0.0,0.0,0.0,0.0,1.0,1.0,Inferiority Language,Stereotypes and Misinformation,Irony,Threatening and Intimidation
2,12834493_1,2,She may or may not be a Jew but she 's certain...,jewish folks are stupid.,she seems to think the Blacks wo n't kill her ...,NFS,NaN,speculation about others' intentions,NaN,NaN,...,1.0,0.0,0.0,1.0,1.0,1.0,Threatening and Intimidation,Irony,Irony,Inferiority Language
3,13251831_1,3,I always thought it would be cool if somebody ...,Indians and Pakis should be killed.,It would be cool if someone secretly detonated...,NFS,NaN,"expresses a wish or hypothetical desire, not a...",NaN,NaN,...,1.0,0.0,0.0,1.0,0.0,1.0,Inferiority Language,Irony,Irony,Incitement to Violence
4,14039975_1,4,Was walking through tooting broadway in SW Lon...,black folks are inferior.,I was the only white person in the area throug...,CFS,false?,"makes a personal, observational claim about a ...",Nigs and pakis were walking down the street sp...,UFS,...,1.0,1.0,0.0,1.0,1.0,1.0,Irony,Threatening and Intimidation,Irony,Inferiority Language
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,31723707_3,224,There is only about 10 niggas in our school an...,black folks and hispanics are inferior.,there are only 10 niggas in our school and 300...,CFS,NaN,NaN,it is the senior year.,CFS,...,1.0,0.0,0.0,1.0,NaN,NaN,Threatening and Intimidation,Threatening and Intimidation,Threatening and Intimidation,Threatening and Intimidation
223,31760414_1,225,Looking at your guys situation makes me realis...,black folks are invading us.,my high school is 100% white.,CFS,NaN,are there schools 100% white?,there are more and more niggas moving into the...,CFS,...,0.0,1.0,0.0,1.0,NaN,NaN,Inferiority Language,Inferiority Language,Irony,White Grievance
224,13480579_1,226,"just saw a hershey 's commercial on tv , ca n'...",jews are inferior.,i just saw a hershey's commercial on tv.,UFS,NaN,NaN,i can't find it on youtube.,UFS,...,0.0,0.0,0.0,0.0,NaN,NaN,Irony,Inferiority Language,Inferiority Language,Threatening and Intimidation
225,13843470_1,227,"These are the latest statistics , Ethnic group...",people of color are inferior.,"irish 87.4%, other white 7.5%, asian 1.3%, bla...",CFS,NaN,NaN,even if that seven percent was all poles.,NFS,...,0.0,0.0,0.0,0.0,NaN,NaN,Stereotypes and Misinformation,Stereotypes and Misinformation,Irony,Stereotypes and Misinformation
226,13850107_1,228,An Irish prison is like a luxury hotel where t...,Immigrants are criminals,An Irish prison is like a luxury hotel.,CFS,NaN,NaN,People don't flee the country if they get caug...,CFS,...,0.0,0.0,0.0,0.0,NaN,NaN,Inferiority Language,Stereotypes and Misinformation,Irony,Stereotypes and Misinformation